### ISSUE TITLE
Allow 0-key newline option in predictive mode

### ISSUE THREAD

**Issue by TomJansen** [sspanak/tt9#102]
In abc modes, the 0 key gives the option to enter a new line. However, in predicitve mode this option is not present.

PS: I think the + sign is a bit lost/random on the 0 key. Or maybe there is a specific reason why it is not under the 1 key.

**Comment by TomJansen** [comment]
When disabling `else if (key == 0) {}` in `onNumber`, the candidate view gives the newline as the first option. I think that space should always be the first option in the candidate view for the 0-key

**Comment by sspanak** [comment]
> When disabling else if (key == 0) {} in onNumber, the candidate view gives the newline as the first option.

You shouldn't be doing this. There is a dedicated `on0()` handler in `TraditionaT9.java`. 0-key has special functions in all modes, so I thought that's the better choice.

>In abc modes, the 0 key gives the option to enter a new line. However, in predicitve mode this option is not present.

> PS: I think the + sign is a bit lost/random on the 0 key. Or maybe there is a specific reason why it is not under the 1 key.

I was thinking it may be a good idea to add some more special characters and perhaps reorganize them. I just wanted to test for some time and see what is missing.

Here is my idea:
- 1-key types the punctuation normally used in sentences: `.!?,;&()'":–` (the last one is a long dash)
- 0-key types a space and special (or technical) characters: `#@%[]{}<>~=*\/+-` (the last one is the minus sign).
- double pressing 0-key is the shortcut for a new line.

**Comment by sspanak** [comment]
Ended up with slightly different lists for both 0 and 1. Also, pressing 0 multiple times just types a space. I figured this is the more convenient option. `\n` is still available as an option when 0 is pressed once.
