### ISSUE TITLE
Consistent look and feel everywhere

### ISSUE THREAD

**Issue by sspanak** [sspanak/tt9#111]
- ~~The suggestions view must use the same colors as the Settings screen~~
- ~~Add Word dialog uses entirely different theme. Change the theme to DayNight, like on the Settings screen.~~
- ~~The soft keys must also follow the standard theming. Probably, the custom backgrounds would have to go away.~~
- ~~Enable the dark/light switch in settings.~~
- ~~Update the user manual.~~

After #29 and #35

**Comment by TomJansen** [comment]
>Add Word dialog uses entirely different theme. Change the theme to DayNight, like on the Settings screen.

Would it be easier to replace the Add Word dialog with an AlertDialog including an edittext box? I made this work but I couldn't seem to float the AlertDialog above the current application transparently.

**Comment by sspanak** [comment]
I've already found a way to keep the current dialog and only change the theme. I am unsure if it would be easier or simpler with an `AlertDialog` given the current one is only some 100 lines long, I haven't tried that. I suppose it is possible to delete the current `xml` and use a standard dialog, but the `AddWordAct` class would have to remain there to do validatation and whatnot.

**Comment by sspanak** [comment]
Note to self: according to [this](https://stackoverflow.com/questions/72382886/system-applies-night-mode-to-views-added-in-service-type-application-overlay)  it is not possible to inflate the main view with a custom theme. The main view of a service is locked to the system theme. This probably means the suggestion and button colours need can only be set programmatically.
