### ISSUE TITLE
Changing the text case in Predictive mode is confusing sometimes

### ISSUE THREAD

**Issue by sspanak** [sspanak/tt9#114]
In Predictive Mode, there are three text cases: uppercase, automatic, lowercase. When we are in the middle of the sentence in automatic text case, the words would appear in lowercase. So, selecting the "next" text case should convert the current word to uppercase. However, the next one in the list is lowercase, which means nothing seemingly happens, even though the setting changes from auto to lowercase. Let's avoid this confusion.

- Rename the "CAPITALIZE" text case to "AUTO" (or something more appropriate)
- When in the middle of a sentence:
  - If the current word contains only capitals, the next mode must be lowercase.
  - If the current word contains only lowercase letters, the next mode is uppercase.
  - If the current word contains mixed case letters, the next mode is lowercase.

**Comment by puffertron** [comment]
I would suggest for the text case and typing modes, maybe have a little indicator on the text bar that tells you what mode you're in, for example, 'ABC', 'abc', '123', 'pred', ':)' for capitalized manual, manual, predictive, and emoji respectively. I think that would be pretty simple to implement as well.

**Comment by sspanak** [comment]
Do you mean like this one?
![language-indicator](https://user-images.githubusercontent.com/27846105/205255993-9c7fb991-10e2-4f52-8309-8be717ba1b54.png)

The built-in keyboard of my phone has sligtly larger and better visible icons and even though I can't figure out how to make mine bigger, I think it is still a clear indicator. Or is it?

The problem described in this bug is a bit different. It is about switching from lowercase to lowercase, which, from user perspective, makes it look like nothing is happening.
