### ISSUE TITLE
OK does not work in the Add Word dialog sometimes

### ISSUE THREAD

**Issue by postpersonality** [sspanak/tt9#136]
Currently when I add a word to a dictionary I have to use touch screen to confirm the word. It would be nice if Ok key would confirm the word in the dialog.

**Comment by sspanak** [comment]
If I press the hardware OK on my phone, it automatically selects the OK of the dialog, then I just need to press it again to add the word. In other words, double pressing OK on the keypad is enough to add the word.

I am unsure if this is Android standard or it's something Xiaomi did on mine. Have you tried double pressing on yours? If it doesn't work, this would be worth implementing, indeed.

**Comment by postpersonality** [comment]
Hmm. It works but not reliably. I found when it doesn't work.
1. Open fresh input
2. Type some word
3. Press asterisk (star)
4. Press ok multiple times

**Comment by sspanak** [comment]
I cannot reproduce it, but I suppose different phones and/or Android versions are not exactly consistent.

Either way, there are two ways of solving this:

1. Define (or fix) the default action of the input field in the Add Word dialog. The OK key is already adjusted to execute the default action if there is one, so it would automatically start working.
2. Modify `TraditionalT9.onOk()` to save the word when the input field has private option `io.github.sspanak.tt9.addword`. This is more of a hack, so option 1. is the better one.

**Comment by sspanak** [comment]
I've changed the title to reflect better the problem we are discussing. I hope you don't mind.

**Comment by sspanak** [comment]
It's all good, no need to do anything fancy. I just fixed the default action and it now works properly. It's just [2 lines of code](https://github.com/sspanak/tt9/pull/141/commits/842e80f7d15e64f02c4ee4f0999706e8b1e574be).

It will be available in the next release. :slightly_smiling_face:
