### ISSUE TITLE
arabic keyboard language

### ISSUE THREAD

**Issue by islam2hamy** [sspanak/tt9#137]
Hi ,

Can you please add arabic keyboard language

Thank you

**Comment by sspanak** [comment]
No, sorry, it is beyond my capabilities. I have no idea how T9 is supposed to work in Arabic (which key should correspond to which letter and how to deal with the different letter forms); nor can I read the language to verify it actually works.

Anyway, if you speak the language, you are welcome to follow the [adding a new language guide](https://github.com/sspanak/tt9/blob/master/CONTRIBUTING.md#adding-a-new-language). If you have at least basic programming skills, it should be fairly easy to add it or at least determine whether the typing engine can support Arabic (I am not even sure about that).

**Comment by sspanak** [comment]
I am unsure why this is closed, but Arabic is certainly not included, so I am reopening it.

Having gained some experience with Hebrew, I think adding Arabic will not be so difficult. At this point I'll need only the following:

1. An example layout (what letter goes on what key), including any special punctuation marks that need to be included or removed from 1-key and 0-key.
2. A good word list containing Arabic words, personal names, names of places and whatnot. Anything that one would type daily.

**Comment by islam2hamy** [comment]
Hello @sspanak ,

please take a look

1. 

2. https://onattech.github.io/Arabic-Keyboard/

**Comment by sspanak** [comment]
Well... I meant a 12-key layout, not a QWERTY layout. You know, which letters are supposed to appear when you press "2", "3", "4", ...; and if there is need to add extra punctuation characters (non-standard to Latin/Cyrillic alphabets).

I really don't know what to do with a computer keyboard layout. :smile:

**Comment by islam2hamy** [comment]
@sspanak , sorry for being late

**Comment by sspanak** [comment]
Sorry, that photo didn't load the last time I opened Github. I see it now. 

However, I was hoping that you (or someone else for that matter) could actually write the appropriate letters/characters for each key. See, I can't read Arabic and it is very difficult for me to compare the letters on your photo with the Wikipedia article about Arabic and figure out the correct ones for 2-key, 3-key and so on, especially given the fact that the font used on your photo is kind of "square", which makes the visual comparison even harder.

**Comment by islam2hamy** [comment]
> Sorry, that photo didn't load the last time I opened Github. I see it now.
> 

No , it is my fault , uploading the photo took time from me

> However, I was hoping that you (or someone else for that matter) could actually write the appropriate letters/characters for each key. See, I can't read Arabic and it is very difficult for me to compare the letters on your photo with the Wikipedia article about Arabic and figure out the correct ones for 2-key, 3-key and so on, especially given the fact that the font used on your photo is kind of "square", which makes the visual comparison even harder.

ok , so you need it like that 

ex.: 2-key = ب ت ة ث

**Comment by islam2hamy** [comment]
3 = ا ء
4 = س ش ص ض
5 = د ذ ر ز
6 = ج ح خ
7 = ن ه و ي
8 = ف ق ك ل م
9 = ط ظ ع غ

**Comment by sspanak** [comment]
Perfect, thanks!

**Comment by islam2hamy** [comment]
You are welcome

**Comment by hemowahib** [comment]
> مرحباً بك

Do you have arabic keyboard language

**Comment by hemowahib** [comment]
> مرحباً بك



> Perfect, thanks!

Hi bro i need arabic keyboard language

**Comment by sspanak** [comment]
No, sorry. I am quite busy with another project and I have no time at all for TT9. I do intend to release Arabic in the future though.

**Comment by Arabi12321** [comment]
I submitted a pull request with the necessary files for arabic support

**Comment by sspanak** [comment]
I am following it, no worries

**Comment by sspanak** [comment]
@Arabi12321, I have created a testing APK with Arabic. Could you please confirm everything is OK. If so, I'll merge it. Here it [the APK](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v27.0+ar.apk). Have in mind, you will have to uninstall the version of Traditional T9 that you are now using, before installing this one.

**Comment by sspanak** [comment]
Yep, I've done some magic to make it work better. I've sorted the words and added frequencies for faster and more accurate predictions.

Thanks to everyone! I am merging the branches. Arabic will officially be part of Traditional T9 in the next release.
