### ISSUE TITLE
Ad Swedish 😀

### ISSUE THREAD

**Issue by ollelars** [sspanak/tt9#144]
Ad Swedish :)

**Comment by sspanak** [comment]
I guess it's "add Swedish". :smile: 

I will need some help to do it:

1. I need to know what is the Swedish layout (what letter is on which key).
2. I need help with translating [the strings](https://github.com/sspanak/tt9/blob/v15.0/res/values/strings.xml), excluding the ones that have the `translatable="false"` attribute (not with Google Translate :wink:). That's optional, though. The UI could remain in English, but it would be nice to have it in Swedish too.
3. Last but not least, I need a good quality list of Swedish words that includes common and not-so-common words, names of geographical objects (cities, lakes, regions, ...), personal names etc, to use it for showing suggestions.
