### ISSUE TITLE
Add ABC mode timeout for same-key characters

### ISSUE THREAD

**Issue by justbruce** [sspanak/tt9#156]
When using ABC mode, it would be helpful if there were a time period after which the currently highlighted character was entered to allow for entry of the next character. 

[For example the domain extension ".edu".  Currently requires 3 additonal key presses to get "ed"] 

Could be a user-selectable thing or hard-coded if that makes more sense

**Comment by sspanak** [comment]
It should definitely be user-selectable. Automatically accepting the selection is one of the most annoying things other keyboards do. I definitely want to keep this option off.

The other reason I haven't done it so far is, because Java makes delayed operations overcomplicated... sadly...

Anyway, I see value in doing this, so it stays on the backlog.

**Comment by sspanak** [comment]
Requirements:

- Add a new preference category: "ABC Mode"
- Add a new on/off option under the new category: "Auto accept selected letter"
  - When on, `SettingsStore` would return timeout of 800 ms.
  - When off, the return value is 3600000 (1 hour).
- Add an `autoAcceptTimeout` in the input modes (or choose another appropriate name).
  - `ModeABC` returns the value from `SettingsStore`.
  - All other modes return 1 hour.
- Implement the auto accept in `TraditionalT9`. It will get the time value from the input mode.

**Comment by felipecrs** [comment]
+1 for this feature, it's the only actually missing thing to be able to fully use this app.

**Comment by qascot** [comment]
I have made this:
in ModeABC.java added `public int autoAcceptTimeout() { return 800; }`
in other modes added `public int autoAcceptTimeout() { return 3600000; }`
in InputMode.java added `abstract public int autoAcceptTimeout();`
in TraditionalT9.java added `	final Handler t9releasehandler = new Handler();
	Runnable mt9release = new Runnable() {
		@Override
		public void run() {
			commitCurrentSuggestion();
			clearSuggestions();
		}
	};`
than in `TraditionalT9.handleSuggestions()` and also in  `previousSuggestion()` and `nextSuggestion()` were added `t9releasehandler.removeCallbacks(mt9release);` and `t9releasehandler.postDelayed(mt9release, mInputMode.autoAcceptTimeout());`
Now testinig how it works and feeling happy. Thanks to sspanak for detailed description in requirements!

**Comment by sspanak** [comment]
I have already started preparing the code base and will soon include the feature officially. Stay tuned!
