### ISSUE TITLE
Add cursor moving by DPAD

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#157]
When there is no suggestions (neither letters no words) it will be very useful to make moving cursor on text by DPAD.

**Comment by sspanak** [comment]
- Rhe `SuggestionsView` is hidden in all cases
- LEFT moves the cursor to the left, RIGHT moves it to the right
- Holding LEFT or RIGHT repeats their function (no special handling)
- Holding UP acts as Home
- Holding DOWN acts as End
- If technically possible, detect when the text is long and wraps on a new line _(not when it contains `\n`!)_ and use UP and DOWN to move the cursor in the respective direction. Once reached the end, allow Android to handle the key to go to the adjacent UI element.

**Comment by justbruce** [comment]
> When there is no suggestions (neither letters no words) it will be very useful to make moving cursor on text by DPAD.

Just FYI, my device [Cat S22 Flip] seems to already do this in the 4 programs I regularly use TT9 with, so it may be device specific.

**Comment by sspanak** [comment]
> Just FYI, my device [Cat S22 Flip] seems to already do this in the 4 programs I regularly use TT9 with, so it may be device specific.

For me it works in some applications, but it doesn't in others, so it must be application-specific. Either way, I find it annoying not being able to move the cursor, so I intend to take look into the issue and make the D-PAD behave the same way in all apps (if possible).

**Comment by qascot** [comment]
From version 17 it works in all apps I use on my DuoQin F21pro. Many thanks!

**Comment by sspanak** [comment]
> From version 17 it works in all apps I use on my DuoQin F21pro. Many thanks!

But I haven't done anything yet 😀. 

And it does not work in Telegram, which I use. The issue stays open for now.

**Comment by sspanak** [comment]
It looks like the big refactoring to change the way input is handled, that took place in versions 21.0 and 22.0 seems to have fixed this. Falling back Android seems to do the trick - the cursor can be moved and there is even simple "Home"/"End" functionality.

Closing this as resolved.
