### ISSUE TITLE
Add Option to harmonize Double-zero behavior with TT9-Old Skool

### ISSUE THREAD

**Issue by justbruce** [sspanak/tt9#168]
Double zero insert is a bit different from the way it used to operate.  If there were an option to set it to the old behaviour it would speed up typing in some instances

Old Skool TT9 had what one could call the expected usage [standard touch keyboards from Apple, Samsung, and Google do it this way (albeit using the actual spacebar, but our spacebar IS the 0 key)]  which is that double pressing zero would insert

1. Backspace
2. [Selected character] (i.e. the newline or period, carat, etc]
3. A space
4. Clear buffer [so that another single space press doesn't cause a repeat of the double-character]

This makes properly ending a sentence or paragraph a much quicker, easier set of keystrokes [keeps your fingers on the lower 12 keys rather than having to reach up to the DPAD] 

It is understood that others may find the current behavior helpful, which is why this should be an option [though we should be careful that we don't want to end up with  a dozen pages of options - but this one is quite an important one]

**Comment by sspanak** [comment]
My initial idea was to have multi-press function, as opposed to double-press, but the more I use it, the more annoying it feels. So, I agree, steps 1, 3 and 4 must be implemented, to make it usable.

Let's do the following when 0-key is pressed for the second time:
- Clear the currently selected character from the first press (1. Backspace)
- If the inserted character belongs to 1-key, adjust the spaces using `TraditionalT9.autoCorrectSpace()`. (3. Space)
- Reset the key repeat status (4. Clear buffer)
- Change the default character to dot, to be consistent with all other keyboards.
- Change back the setting name from "multi press" to "double press"
- Update the documentation

**Comment by sspanak** [comment]
I think I made it work properly. @justbruce, feel free to try out [beta-16.3](https://github.com/sspanak/tt9/releases/tag/beta-16.3) and let me know if something is still missing.

**Comment by justbruce** [comment]
> I think I made it work properly. @justbruce, feel free to try out [beta-16.3](https://github.com/sspanak/tt9/releases/tag/beta-16.3) and let me know if something is still missing.

I get the backspace and the selected double space character, but not the additional space after it.  

The repeat status does appear to be reset, which I find exceedingly helpful

**Comment by sspanak** [comment]
> I get the backspace and the selected double-0 character, but not the additional space after it.

Have you enabled the "Automatic Space" from the Settings screen? It is off by default.

**Comment by justbruce** [comment]
> > I get the backspace and the selected double-0 character, but not the additional space after it.
> 
> Have you enabled the "Automatic Space" from the Settings screen? It is off by default.
> 
> Edit: you may want to try the new [beta-16.5](https://github.com/sspanak/tt9/releases/tag/beta-16.5).

I have now - working great.

Should the documentation be updated to reflect this behavior? I would not have expected it to factor in, but maybe my expectations aren't quite average...

**Comment by sspanak** [comment]
> Should the documentation be updated to reflect this behavior? I would not have expected it to factor in, but maybe my expectations aren't quite average...

I don't know really. I am hoping the settings have good names and descriptions that make them self-explanatory. That's the reason I haven't described anything in the manual.
