### ISSUE TITLE
Brazilian Portuguese input

### ISSUE THREAD

**Issue by Nightly-Luke** [sspanak/tt9#179]
Hello, I would like to ask for Brazilian Portuguese support :)

About the keys:

Apostrophes are part of words (like "d'água")
Key 2 - abcçáâãà
Key 3 - deféêè
Key 4 - ghií
Key 5 - jkl
Key 6 - mnoóôõ
Key 7 - pqrs
Key 8 - tuvú
Key 9 - wxyz

I can provide menu translations too, and a good dictionary (but I don't know how to send them to the project).
Brazilian Portuguese is different from Portugal Portuguese, so the icon can be the string "BR".

Thank you so much for taking the project on, I appreciate it so much :)

MAINTAINER EDIT: Add the language after #192 to avoid conflicts.

**Comment by Nightly-Luke** [comment]
This dictionary is a list of all PT-BR words, and get constantly updated:
https://www.ime.usp.br/~pf/dicios/
"br-utf8.txt" is the updated dictionary :)
It uses GNU Public License and is hosted by Institute of Matemathics and Statystics of USP (University of São Paulo). Both linked in the page


About the menu, I made the translation:
`<?xml version="1.0" encoding="utf-8"?>
<resources>
	<string translatable="false" name="help_url">https://github.com/sspanak/tt9/blob/master/docs/user-manual.md</string>
	<string name="app_name" translatable="false">Traditional T9</string>
	<string name="app_settings">Configurações do Teclado</string>
	<string name="completed">Concluído</string>
	<string name="error_unexpected">Um erro inesperado aconteceu.</string>

	<string name="add_word_add">Adicionar</string>
	<string name="add_word_blank">Palavra em branco, impossível adicionar.</string>
	<string name="add_word_exist">Palavra \"%1$s\" já está registrada.</string>
	<string name="add_word_invalid_language" translatable="false">Cannot add a word when no language is selected</string>
	<string name="add_word_title">Adicionar Palavra</string>
	<string name="add_word_field_placeholder">Escreva uma palavra</string>

	<string name="pref_category_about">Sobre</string>
	<string name="pref_category_appearance">Aparência</string>
	<string name="pref_category_dictionaries">Dicionários</string>
	<string name="pref_category_predictive_mode">Modo Predictivo</string>
	<string name="pref_category_function_keys">Atalhos</string>
	<string name="pref_category_keypad">Teclado</string>

	<string name="pref_auto_space">Espaçamento Automático</string>
	<string name="pref_auto_space_summary">Insere um espaçamento após ponto final.</string>
	<string name="pref_auto_text_case">Maiúsculas Automáticas</string>
	<string name="pref_auto_text_case_summary">Inicia automaticamente com letras maiúsculas.</string>
	<string name="pref_choose_languages">Idiomas</string>
	<string name="pref_dark_theme">Modo Escuro</string>
	<string name="pref_double_zero_char">Caractere para toque múltiplo na tecla 0</string>
	<string name="pref_show_soft_function_keys">Mostrar teclas de funções na tela</string>
	<string name="pref_help">Ajuda</string>

	<string name="dictionary_cancel_load">Cancelar Carregamento</string>
	<string name="dictionary_load_bad_char">Falha no carregamento. \"%1$s\" na linha %2$d do idioma \"%3$s\".</string>
	<string name="dictionary_load_error">Falha no carregamento do dicionário para o idioma \"%1$s\" (%2$s).</string>
	<string name="dictionary_load_cancelled">Carregamento de dicionário cancelado.</string>
	<string name="dictionary_loaded">Dicionário carregado com sucesso.</string>
	<string name="dictionary_loading">Carregando dicionário (%1$s)…</string>
	<string name="dictionary_loading_indeterminate">Carregando dicionário...</string>
	<string name="dictionary_load_title">Carregar Dicionário</string>
	<string name="dictionary_missing_go_load_it">Não há um dicionário para o idioma \"%1$s\". É possível carregá-lo em "Configurações".</string>
	<string name="dictionary_not_found">Falha no carregamento. Não foi encontrado um dicionário para o idioma \"%1$s\".</string>
	<string name="dictionary_truncate_title">Limpar Dicionário</string>
	<string name="dictionary_truncated">Dicionário apagado com sucesso.</string>

	<string name="function_add_word_key">Adicionar palavra</string>
	<string name="function_backspace_key">Backspace</string>
	<string name="function_next_language_key">Próximo Idioma</string>
	<string name="function_next_mode_key">Modo de Entrada</string>
	<string name="function_show_settings_key">Entrar em Configurações</string>
	<string name="function_reset_keys_title">Restaurar Atalhos Padrão</string>
	<string name="function_reset_keys_done">Atalhos Restaurados.</string>

	<string name="key_hold_key">(segurar)</string>
	<string name="key_none" translatable="false">--</string>
	<string name="key_back">Voltar</string>
	<string name="key_call">Chamada</string>
	<string name="key_delete" translatable="false">Delete</string>
	<string name="key_f1" translatable="false">F1</string>
	<string name="key_f2" translatable="false">F2</string>
	<string name="key_f3" translatable="false">F3</string>
	<string name="key_f4" translatable="false">F4</string>
	<string name="key_menu" translatable="false">Menu</string>
	<string name="key_pound" translatable="false">#</string>
	<string name="key_star" translatable="false">✱</string>

	<string name="char_dot" translatable="false">.</string>
	<string name="char_newline">Nova Linha</string>
	<string name="char_space">Espaço</string>
</resources>`

Made it in my free time, I'll translate the remaining documents soon (user manual, readme and contributing)

Thank you so much! People like you keep the world getting better. I'm glad to contribute with it :)
I'm using this app in a Qin F21 Pro. It's very useful to people that have some limitations with touch screens, like shaking hands.

**Comment by sspanak** [comment]
> Made it in my free time, I'll translate the remaining documents soon (user manual, readme and contributing)

Excelent! I'll include it as soon as I have time. 

But please, hold on with the document translations. They are available only here, on Github, and in order to navigate in Github, people still need to know English. And if they do, it wouldn't matter much to them if the documents are translated or not.

The manual is indeed for regular ordinary people, but at the moment there is no good way of displaying it if it is in another language.

Thank you again for your contribution!

**Comment by Nightly-Luke** [comment]
Nice! I'm open to help with more translations in the future 🙂
I'll learn more how to get with pull requests and more git stuff. This is the first project that I contribute and I'm amazed to see how an open source project really works.

**Comment by sspanak** [comment]
@Nightly-Luke, I am almost ready with adding the language. However, since I have added some new stuff, there are already discrepancies in the translations.

If you would like these to be included, please translate them:
```
<string name="pref_upside_down_keys">Reverse Key Order</string>
<string name="pref_upside_down_keys_summary">Use this if you have 7–8–9 on the first row, instead of 1–2–3.</string>
<string name="dictionary_truncate_unselected">Clear Unselected</string>
```

The last is in this context: "clear the dictionaries for the languages that are not selected". It is an extra option available since version 18.0.

Also, I changed: "Caractere para toque múltiplo na tecla 0" to "Caractere para toque duplo na tecla 0". I hope this sounds correct.

**Comment by Nightly-Luke** [comment]
Thank you so much for the attention! I'll install that .apk and test for some days 😄 

About the new options, here's the translation: 

`<string` name="pref_upside_down_keys">Inverter Ordem das Teclas</string>
<string name="pref_upside_down_keys_summary">Utilize essa opção se você possuir as teclas 7–8–9 na linha de cima, ao invés de 1–2–3.</string>
<string name="dictionary_truncate_unselected">Limpar Não Selecionados</string>`

About the change to "toque duplo", that's correct! It sounds more accurate to "double tap". "Toque múltiplo" sounds more like "multiple tap"

**Comment by Nightly-Luke** [comment]
I've been testing the app for the last week and it is working fine. I had no problems using it :)
Thank you so much again! 😄

**Comment by sspanak** [comment]
Excelent! Stay tuned for the new v19.0 which will officially support the language.
