### ISSUE TITLE
Suggest the second most popular word when typing the same sequence two times in a row

### ISSUE THREAD

**Issue by sspanak** [sspanak/tt9#184]
In some languages, for example Bulgarian, there are commonly used words that share the same sequence `за`/`да`, `се`/`те`; English: `on`/`no`, `go`/`in`; French: `je`/`le`, `me`/`ne`, and so on. It is very unlikely that someone would want to type the same word twice, so:

- Let's swap the two most popular suggestions, when the same sequence has been typed twice in a row.
- Consider not updating the word frequency in this case.

**Comment by justbruce** [comment]
I think not updating the word frequency is the way to go.  For frequently used words, having the two most popular selections constantly swapping positions slows down typing speed. By not updating the frequency, plus having this as a option, typing speed actually has a chance to speed up.

**Comment by sspanak** [comment]
Benchmark results on Sonim XP3800:

```
// Test 1
Loaded 1000 word pairs for language: 453
Loaded 894 word pairs for language: 596550
Loaded 999 word pairs for language: 231650
Loaded 2893 word pairs in 422 ms

// Test 2
Loaded 1000 word pairs for language: 453
Loaded 894 word pairs for language: 596550
Loaded 999 word pairs for language: 231650
Loaded 2893 word pairs in 286 ms

// Test 3
Loaded 1000 word pairs for language: 453
Loaded 894 word pairs for language: 596550
Loaded 999 word pairs for language: 231650
Loaded 2893 word pairs in 122 ms
```

Save times are 750 ms - 1000 ms.

Word length is between 1 and 6 letters, max words are 1000 per language. Given that loading and saving happens in a background thread, performance is very acceptable. Keeping these limits.

**Comment by sspanak** [comment]
It turned out searching is too slow, causing typing lag. Today's optimization reduce searching and adding time to 1 ms. Loading time is 160-480 ms, while saving time is 700-1300 ms.
