### ISSUE TITLE
Not Showing as IME Option (KK 4.4.2)

### ISSUE THREAD

**Issue by levone1** [sspanak/tt9#198]
Probably not an issue with the app, but maybe you know...

Messing around with an old KitKat phone, and installed tt9.  Installed fine, but won't show up as an input method, (no way to choose it from Settings > Language and Input > Select Input Method).  It shows as installed in apps list, and I can launch tt9 Settings from activity launch app or terminal, but the phone doesn't "see" it as an IME handler...

Sonim XP5; Android 4.4.2

Any ideas?

**Comment by sspanak** [comment]
No, I have no idea. I have just tried installing it on my 4.4.2 tablet and it showed up under the IMEs list, without me doing anything special.

Perhaps your phone has custom IMEs disabled deliberately. Have you tried installing any other keyboard, for example, OpenBoard or AnySoftKeyboard? Do they appear in the list?

**Comment by levone1** [comment]
> No, I have no idea. I have just tried installing it on my 4.4.2 tablet and it showed up under the IMEs list, without me doing anything special.
> 
> Perhaps your phone has custom IMEs disabled deliberately. Have you tried installing any other keyboard, for example, OpenBoard or AnySoftKeyboard? Do they appear in the list?

Using Airdroid successfully on Windows and on Linux, both with desktop app, and Airdroid Web.  It works by enabling Airdroid as an IME, but it doesn't actually have any keyboard; it shows up on the list, though...  Is there some kind of mime-type thing I could force mod?

Thanks

**Comment by sspanak** [comment]
> Using Airdroid successfully on Windows and on Linux, both with desktop app, and Airdroid Web. It works by enabling Airdroid as an IME, but it doesn't actually have any keyboard; it shows up on the list

I have never used Airdroid and I have no idea how it works. Please, try installing one of the keyboards I noted above and let me know if it works.

Alternatively, try out [K9T9](https://github.com/danielshorten/k9t9). In the manual there are instructions how to switch the default IME using `abd`, even if you don't have menus for that. You could attempt the same with TT9. The package name is: `io.github.sspanak.tt9`

> Is there some kind of mime-type thing I could force mod?

If something is missing, it is probably in `AndroidManifest.xml`, but I have no idea what could it be.

**Comment by alexknop** [comment]
I came across the same issue. I am using a Sonim XP3 on Android 8.1
When I visit "Languages & Input", under "Keyboards & Input methods" are FlexT9 Text Input (default for the Sonim) and nothing else. I did find a workaround. I downloaded Old T9 Keyboard (an app developed by Meditaide).  Then I had to open the Old T9 app from my Applications list and go through a Getting Started demo, which then showed the "Available virtual keyboard" page which looked like an Android system settings page, where I can see FlexT9, Old T9, and Traditional T9. Old T9 and Traditional T9 were both disabled and I was able to toggle both on. Now I can see Traditional T9 under "Keyboards & Input methods"

So I think one issue is there isn't "Traditional T9" in the apps list on my phone. No way for me to open it and enable such a setting as the virtual keyboard. That would be where to start, I believe.

**Comment by sspanak** [comment]
> Old T9 and Traditional T9 were both disabled and I was able to toggle both on. Now I can see Traditional T9 under "Keyboards & Input methods"

What happens if you turn them off from the "secret" screen? Do they remain visible in the standard "Keyboards & Input methods" regular screen?

**Comment by levone1** [comment]
> I came across the same issue. I am using a Sonim XP3 on Android 8.1 When I visit "Languages & Input", under "Keyboards & Input methods" are FlexT9 Text Input (default for the Sonim) and nothing else. I did find a workaround. I downloaded Old T9 Keyboard (an app developed by Meditaide). Then I had to open the Old T9 app from my Applications list and go through a Getting Started demo, which then showed the "Available virtual keyboard" page which looked like an Android system settings page, where I can see FlexT9, Old T9, and Traditional T9. Old T9 and Traditional T9 were both disabled and I was able to toggle both on. Now I can see Traditional T9 under "Keyboards & Input methods"
> 
> So I think one issue is there isn't "Traditional T9" in the apps list on my phone. No way for me to open it and enable such a setting as the virtual keyboard. That would be where to start, I believe.

Thanks...  Seems like clearly phone-specific for me.  I have tried installing a few different keyboards, just to test, (including the one you mentioned).  All install without error, and open, (if they have an icon), but whenever I get to the "enable input method" screen, nothing is there except the default flext9.  Funny because somehow Airdroid is able to get in there and enable itself so I can use it, and when I go to "select default input method", there is an option for flext9 or Airdroid, but when I go to "manage input methods", there are none shown except flext9, (not even Airdroid).  There's probably an adb shell command that could enable an input method, so that it will then show up on the list of defaults, but I can't find a way to enable anything through settings...

**Comment by levone1** [comment]
Update - figured it out from this https://android.stackexchange.com/questions/47948/how-to-change-input-method-with-ime-command

enter from adb: `adb shell ime enable io.github.sspanak.tt9/.ime.TraditionalT9`

Now it shows up as an option for default...

Thanks

**Comment by alexknop** [comment]
> > Old T9 and Traditional T9 were both disabled and I was able to toggle both on. Now I can see Traditional T9 under "Keyboards & Input methods"
> 
> What happens if you turn them off from the "secret" screen? Do they remain visible in the standard "Keyboards & Input methods" regular screen?

Once I turn Traditional T9 off from the "Available virtual keyboard" screen, then Traditional T9 is no longer in the "Keyboards & Input methods" screen. It appears to be dependent

**Comment by alexknop** [comment]
> > Old T9 and Traditional T9 were both disabled and I was able to toggle both on. Now I can see Traditional T9 under "Keyboards & Input methods"
> 
> What happens if you turn them off from the "secret" screen? Do they remain visible in the standard "Keyboards & Input methods" regular screen?

Secondly, I also have to change my keyboard to Traditional T9, otherwise FlexT9 is still the default. The only way I can do this as of now is again in the Old T9 app. After choosing keyboards to enable/disable, the app then asks "Change keyboard" and has radio buttons to select a default. This is where I also have to select Traditional T9. Now it comes up by default.

**Comment by sspanak** [comment]
@alexknop, @levone1, I have one more question before closing this discussion.

From what I understand, Sonim displays its own, non-standard keyboard settings screen, where they wanted to display only their own keyboard. I suppose many other phone work the same way.

So... I was thinking... It is easy to add a launcher icon, so one could open the TT9 Settings. From there, I could add a button to go to Android Settings or possibly, directly enable the keyboard. People [say it is possible](https://stackoverflow.com/questions/52126044/programmatically-enabling-a-custom-keyboard).

I believe this would be a valueable update. What do you think?

**Comment by alexknop** [comment]
A launcher icon would be beneficial since there wasn't anything natively in the settings for me to enable Traditional T9.
I believe for my phone (and some others) the Traditional T9 app would need to follow the same steps as the Old T9 application and prompt the user to enable the keyboard via "Available virtual keyboard" in Android's settings, as well as changing their default keyboard via "Change keyboard" in Android's settings.
These are the two screens I am talking about:
![Screenshot_20230307-105450](https://user-images.githubusercontent.com/11878115/223475999-f41890ca-85d9-4a60-b0aa-b6d088df59bd.png)
![Screenshot_20230307-105502](https://user-images.githubusercontent.com/11878115/223476012-ea64b27b-9c13-4736-a2d0-10720d7acd00.png)

**Comment by levone1** [comment]
> @alexknop, @levone1, I have one more question before closing this discussion.
> 
> From what I understand, Sonim displays its own, non-standard keyboard settings screen, where they wanted to display only their own keyboard. I suppose many other phone work the same way.
> 
> So... I was thinking... It is easy to add a launcher icon, so one could open the TT9 Settings. From there, I could add a button to go to Android Settings or possibly, directly enable the keyboard. People [say it is possible](https://stackoverflow.com/questions/52126044/programmatically-enabling-a-custom-keyboard).
> 
> I believe this would be a valueable update. What do you think?

Yes, would be nice...  But I'm fine now, knowing the adb command.  Obviously it is possible, since that is how Airdroid works.  I guess you just program a permissions box to pop up, and if 'ok' is clicked, the above adb command is run, and now the ime is enabled...

**Comment by sspanak** [comment]
Exactly, what I am thinking!

**Comment by sspanak** [comment]
The linked PR solves the issue. Now TT9 will allow access to Android settings. No more hacks using abd are needed.
