### ISSUE TITLE
Input timeout feature

### ISSUE THREAD

**Issue by yant0** [sspanak/tt9#200]
I used to use a keyboard which does not have an ok feature for letters i want for it to stop on. Instead it uses a timeout feature where if you dont press on any key for a period of time, it will lock the current letter. Its also pretty convinient for me because i dont have a touch screen phone and my phone emulates a mouse cursor so it does not accept the OK input.

Thanks for the fork :)

also, i only want the feature in the ABC mode since i dont think it will fit in with the other modes

**Comment by sspanak** [comment]
This is the same as #156.

> Thanks for the fork :)

I am glad you like it. I'll eventually get to your request too, but it will take some time.
