### ISSUE TITLE
Add an option to select candidates by DPAD left/right

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#201]
I’ve tried to change suggestion selection from Up/Down to Left/Right and found that more intuitive if selection highlight moves right when DPAD Right pressed and moves left when DPAD Left pressed. I guess that there may be phones with only Up/Down buttons and without Left/Right, so maybe you can add an option «Candidate Selection» with Up/Down and Left/Right variants.

**Comment by sspanak** [comment]
> ... so maybe you can add an option «Candidate Selection» with Up/Down and Left/Right variants.

That's one way of doing it. 

But with this kind of option, it will not be immediately obvious how to use Filter/Clear Filter with the other key pair. So, maybe, I am thinking of adding a "DPAD" or "Arrows" section on "Select Hotkeys" screen, where one could select the actions for each arrow key (or disable them completely, for that matter). 

What do you think?

**Comment by qascot** [comment]
Your idea is perfect, I think.

**Comment by sspanak** [comment]
We've got a deal.

**Comment by sspanak** [comment]
> Will this section have different actions for different modes?

I haven't thought about it, but it is an interesting idea. But I think, the more appropriate issue for this is #157.
