### ISSUE TITLE
"I" as default in English dictionary

### ISSUE THREAD

**Issue by alexknop** [sspanak/tt9#205]
Hello,

It would be better if when a user presses 4, "I" is the default option, not h. Currently it is hgI. 
Secondly, a lowercase i would be nice. 
To put it all together, when a user presses 4, the suggestions should be I g h i with I being the first/default option.

**Comment by sspanak** [comment]
1. In Predictive mode (which I assume you are using), there is no strict suggestion order. As you type, TT9 "learns" and suggests words or letters that you use more often at the beginning of the list. So, once you select "I" a couple of times it will start appearing first. Just keep typing and don't think too much about. It will magically guess what you are thinking. :wink: 
2. You can toggle the suggestions case with the "#" key. Type something and before accepting it with OK, press "#" to change it to upper- or lowercase. See [the manual](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#next-input-mode-key-default-press-) for more info about the keypad controls.

**Comment by sspanak** [comment]
> I still think a lowercase i would be nice along with the capital I in the suggestions

At the moment, it is technically impossible.

> ... so that if people want to manually type a word starting with i, they won't have to go through the extra button press of #.

There is no need to do that, if you have "Automatic Capitals" setting enabled. As long as it is on, the words will default to lowercase, but the first word in sentences and the personal names will automatically become capitalized (unless you enforce uppercase, for example). So, you don't need to worry about changing the text case.

As I said, just keep typing and let the magic happen. TT9 will make sure you don't press extra keys, unless it is really necessary.

Now, what I explained does not work so well in all languages, in particular French, Italian, Russian, Ukrainian. Unfortunatelly, their dictionaries are not so good as English, for example. But, if I understand correctly, you are using English, so you should be fine.

**Comment by alexknop** [comment]
> There is no need to do that, if you have "Automatic Capitals" setting enabled. As long as it is on, the words will default to lowercase, but the first word in sentences and the personal names will automatically become capitalized (unless you enforce uppercase, for example). So, you don't need to worry about changing the text case.

What I'm saying is lets say in the middle of the sentence you wanted to type the word "iyers" but it isn't in the dictionary. Your first want is to insert a lowercase i. In this case, you would have to change the case because when you press 4, "I" is the only i available. 
This is what I think would help the user more (seen on other keyboards):
![image](https://user-images.githubusercontent.com/11878115/223480258-1af06d49-9afb-4446-98a3-4a6ee05b1c97.png)
![image](https://user-images.githubusercontent.com/11878115/223480333-d08d1dcb-3bab-4cad-9eef-61f94d49359a.png)
see how I and i are in there.

**Comment by sspanak** [comment]
> see how I and i are in there.

As I said, this is currently impossible. In order to do it, I'll have to implement per-language typing rules, which means completely rethinking how TT9 works and redoing it. This is way too much effort, for a not-so-common scenario in only one language. I don't think it is worth the effort. At least, not now.
