### ISSUE TITLE
OK button function

### ISSUE THREAD

**Issue by alexknop** [sspanak/tt9#206]
I think pressing OK/select should insert characters/words but then not add a space after them.
Instead, that function should be left for the space key (usually the 0 key).
That way, users can manually enter a word that is not suggested by entering one letter at a time and pressing OK/select and not have to worry about a following space.

**Comment by sspanak** [comment]
1. Go to Settings -> Keypad. 
2. Scroll down to Predictive Mode category 
3. Disable "Automatic Space"

Now the spaces are completely under your control.

**Comment by alexknop** [comment]
Perfect! thank you.
