### ISSUE TITLE
Importing / Exporting personal dictionary

### ISSUE THREAD

**Issue by TheProgrammer26** [sspanak/tt9#208]
Can you find a solution for losing the personal dictionary when you update the keyboard? 
The solution I found was to add the capability to import and export the user's dictionary. 
If there is any other solution please let me know.
Thanks

**Comment by TheProgrammer26** [comment]
How should I update it? ( I previously just installed the new apk file.)

**Comment by sspanak** [comment]
That's it. Just download and install the latest APK or use IzzyOnDroid, if you have F-Droid. 

I'll eventually release it "officially" on F-Droid, but so far, I haven't had the time to do so.

**Comment by TheProgrammer26** [comment]
Thanks for the confirmation. I tried to do it, but it deleted my words in
the personal dictionary. Do you any way I can resolve this issue?

**Comment by sspanak** [comment]
> I tried to do it, but it deleted my words in the personal dictionary

What is the "personal dictionary", btw? When you add words they are just appended to the built-in list of words. There is no distinction between "custom" and "factory" words.

The only scenarios I can imagine are:
1. You have used the "clear" function then you have reloaded the words.
2. You have uninstalled and reinstalled the application.

In both cases, there is no turning back. Sorry!

Or are you are talking about the personal dictionary that's part of Android and that some other keyboards use? If yes, it is not compatible with TT9 and words in it have never and will never appear as suggestions.

Either way, if you have compiled a list of new words, please, don't keep them for yourself, but share them with the community. My belief is TT9 should come with a good enough dictionary, so users shouldn't worry too much about managing the words themselves. Adding several rarely used words can't be avoided, of course. But the common ones should be there, available to anyone.
