### ISSUE TITLE
Selecting Suggested Contact with OK

### ISSUE THREAD

**Issue by alexknop** [sspanak/tt9#210]
I am trying to compose a new text message and in the To field I am putting in the name of a contact. I can insert the letters I want and then move down and highlight the contact but when I press OK, it is trying to select what I have typed so far and not the contact.

This is happening in ABC or T9 mode and is happening whether I show or hide the on-screen keys.

My default keyboard is not doing this.
Typing O:
![image](https://user-images.githubusercontent.com/11878115/224103854-fac87914-23a0-4d70-9b76-819a6df3fa54.png)

After selecting the first contact (wants to send to O):
![image](https://user-images.githubusercontent.com/11878115/224103909-ae4196bb-cb2d-403b-9e4d-cfbd3e4bcd87.png)

My default keyboard acts like so:
Typing O:
![image](https://user-images.githubusercontent.com/11878115/224104041-63ed2395-9ff0-4dad-8946-e79446856ca3.png)

After selecting the first contact (selects the contact):
![image](https://user-images.githubusercontent.com/11878115/224104120-c35ce274-e8ba-4b5a-829a-4453af0c2d92.png)

It seems that maybe the OK button, even when suggestions are not showing, is programmed to "Enter" the O as the desired entry and it no longer acts as a select key.

**Comment by sspanak** [comment]
After improving the way the DPAD works in #157 and #201, this may become OK, too.

**Comment by alexknop** [comment]
fixed in PR #309
