### ISSUE TITLE
Selecting text when the keyboard is inactive deletes selected word when the keyboard starts

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#252]
When open any app to edit text and double tap on text (with enough speed) while keyboard is inactive, the surrounding tap zone word is being deleted.
This does not happen if another keyboard is set by default. Usually the surrounding word is being selected in this case.

**Comment by qascot** [comment]
I guess this happens when double tap makes selection on text before the tt9 is started. And on tt9 start the new text field is adding instead of selection. Maybe make existing text editable instead of set new text field is the key to the way to leave the selection in the text. However, you can just get used to pressing once before you start typing.

**Comment by sspanak** [comment]
I've tested a bit and it looks like some in some application the text does get erased, but in others it gets selected or simply nothing happens. As a matter of fact, I was only able to replicate it in Telegram on my touchscreen phone.

I guess this can be considered a bug, but it is really a very specific scenario, so I'll consider it very low priority. Just tap once and it will be fine, I am not sure why would you double tap. :slightly_smiling_face:

**Comment by sspanak** [comment]
Alright, this is easy enough to reproduce, so let's fix it.
