### ISSUE TITLE
Accented letters

### ISSUE THREAD

**Issue by mackay508** [sspanak/tt9#253]
Apologies if this has been suggested or implemented but i couldnt see/find it. Would it be possible to add accents like à é etc to the app? It would make it easier to type in multipule languages without needing to load different languages.

**Comment by sspanak** [comment]
This is not possible. 

T9 keyboards always type digits, then convert the digit sequence to the words in the selected language. Hence, to type a word in a different language, you must have it loaded.

**Comment by jgdye** [comment]
What about in abc mode?  I've had bar phones that did it where they would put the accented characters after the number.  (Preferably as an option, so if someone doesn't use the accented characters at all they wouldn't need to scroll through them after pressing one too many times)

**Comment by sspanak** [comment]
Sorry, this is out of the question. If you need to type in another language, just switch to that language.

**Comment by gabriel-tandil** [comment]
I understand that you can add the language without loading the dictionary (and switch to this language when needed), I don't know if it works for your case.

**Comment by sspanak** [comment]
Absolutely. If you just need to type one character in a different language, by only enabling the language and using its ABC mode.
