### ISSUE TITLE
Save capital letters in words added to dictionary

### ISSUE THREAD

**Issue by coolgmr** [sspanak/tt9#256]
Hi,

I couldn't find this had been suggested before.

Would it be possible that when adding words to the dictionary of predictive text, that it would remember if there were any capital letters in that word?

e.g. I saved the name "Luca" to the dictionary, but when I re-type it in the predictive text mode, it displays "luca" without a capital "L".

**Comment by joddsus** [comment]
This has been a major annoyance for me as well, and with no option to
change to Abc in dictionary mode, typing names is a hassle.

**Comment by coolgmr** [comment]
> change to Abc in dictionary mode, typing names is a hassle.

I seem to be able to change to Abc in dictionary mode but even when I save the name with a Captial letter, it doesn't save that information in the dictionary...

e.g. I saved the name "Luca" to the dictionary, but when I re-type it in the predictive text mode, it displays "luca" without a capital "L".

**Comment by sspanak** [comment]
>Would it be possible that when adding words to the dictionary of predictive text, that it would remember if there were any capital letters in that word?

It is possible, yes. And I guess, doing this will also require a functionality for deleting old/wrong words.
