### ISSUE TITLE
Non-number long-press functionality on KYF33

### ISSUE THREAD

**Issue by mcfrei** [sspanak/tt9#264]
What would be the best way to include dialer-specific functionality for KYF33, namely:
1) long press on `*` button produces `+` symbol
2) long press on `#` button produces `;` (pause) symbol

Currently this requires code modification and for me looks like the best way would be to have a "keymap" option for [123] and [Dialer] modes, where for each hardware key different functionality can be added for short press, long press, and double press internally, with it being set up by default during first launch but still available to change in settings. But that requires a lot of code refactoring and I'm not sure you are fine with it.

Alternatively, one can add a `, boolean hold, int repeat` to `onOtherKey` and process hold event in `ModeDialer` (it's what I have in my branch now) but that's kind of bad practice, even if wrapped in an option enabled check.

**Comment by mcfrei** [comment]
![KYF33](https://github.com/sspanak/tt9/assets/37238771/9de8aba8-c488-453b-874c-234975e23f71)

**Comment by sspanak** [comment]
This is related to #261. See my comment there.

**Comment by mcfrei** [comment]
fixed and working flawlessly in 09e5e1b (v 22.0)
