### ISSUE TITLE
Danish keyboard language

### ISSUE THREAD

**Issue by d779224dk** [sspanak/tt9#266]
Hi,

Would it be possible to add danish t9 keyboard language?
I have been looking at the guide, but doesn't have the skills to do it myself.
I would much appreciate it.. There's no rush.
Thanks.

**Comment by joddsus** [comment]
I am planning to contribute to this at some point, just toddlers and babies
plus work keeps making me postpone it.

**Comment by sspanak** [comment]
> Would it be possible to add danish t9 keyboard language?

Absolutely, Danish ought to be an easy one. I guess I could include it sooner than later.
