### ISSUE TITLE
If the “Call” button is selected as the “Backspace“ hotkey, it does not work in the Dialer either as “Backspace" or as “Call".

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#285]
I use the “Call” button as a “Backspace“ on my Qin F21pro. This is very practical, because this button is not used in almost all cases. Other possible hotkeys are not very convenient for me to use. "Back" in some apps are intercepted by the system and do not work as "Backspace". The "Menu" button is more useful for its system function. One day I wanted to dial a phone number that was not included in my contacts. Pressing the "Call" button on the main screen opens the dialing program, pressing the "Digits" dials the phone number (the "Back" button works as a "Backspace" according to the system function). And when the phone number was dialed, I didn't find a way to call. The “Call” button does nothing, and there are no soft buttons or menu function "Call" in the standard dialer.
I found a solution of this issue by changing the 'onBackspase' boolean. I have made this: `	public boolean onBackspace() {
		if (mEditing == EDITING_DIALER /*|| !textField.isThereText()*/) {
			Logger.d("onBackspace", "backspace ignored");
			mInputMode.reset();
			if (Key.isHotkey(settings, KeyEvent.KEYCODE_CALL)) {
				super.sendDownUpKeyEvents(KeyEvent.KEYCODE_CALL);
			} else {return false;}
		}`
This may not be the best solution, but it seems to work well. Please check if you could add this or make it in a better way.

**Comment by sspanak** [comment]
It sounds to me this related to: #241 and #261. I think I have fixed them all - it's all good on my F21 Pro, but I haven't been able to confirm it on Kyocera or LG. Still, at least the code looks much better, if not anything. :smile: 

Anyway, you may want to wait until next week, when v22.0 is coming. Or, if you prefer building from source, use the latest `master`. I can see you are a couple of commits behind, so you are definitely seeing some bugs that have already been fixed.

**Comment by qascot** [comment]
Maybe I see some bugs that have already been fixed. In v21, this issue is present. I checked. I'm looking forward to v22.

**Comment by qascot** [comment]
Tried from source code. There is no this issue, thank you.
