### ISSUE TITLE
Add Greek language

### ISSUE THREAD

**Issue by AgentGolder** [sspanak/tt9#288]
Hello.
I bought a Cat S22 phone, (unlocked from E-bay) and I need to write in Greek as I could on the older Nokia ones and the LG Wine smart.
I'M totally blind and prefering these devices because of the traditional alphanumeric keypad which have.
I've already switched the display language by using another app but not the keypad yet.
Can you pleas add the Greek language also or tell me what to do because I don't know how to program?
So far, haven't found any similar app for such cases. There are for older Android versions which are discontinued.
Thanks for diveloping this project and waiting for your responce.
Best regards.

**Comment by sspanak** [comment]
> Can you pleas add the Greek language also or tell me what to do because I don't know how to program?

If you have no technical skills, it would take more time for me to explain, instead of doing it. Anyway, you could still check the [Adding a new language guide](https://github.com/sspanak/tt9/blob/master/CONTRIBUTING.md#adding-a-new-language).

**Comment by sspanak** [comment]
@AgentGolder, I checked my old Nokia 3310, that I always use for reference. The Greek layout there is:

0. Space, Enter, Math
1. Punctuation
2. αβ
3. δεφ
4. ηγι
5. κλ
6. ομνω
7. σςπρψ
8. θτ
9. χζυξ

Is this correct? It looks out of order, but I guess, it may be like Hebrew, where the layout is not in alphabetical order for convenience.

**Comment by AgentGolder** [comment]
Thanks for your responce.
The correct is:
1. Panctuation
2. αβγά2
3. δεζέ3
4.  ηθιήίϊΐ4
5. κλμ5
6. νξοό6
7. πρσς7
8. τυφύϋ8
9. χψωώ9
Please add it and let me know where is the .apk file to get it.
Best regards.

**Comment by AgentGolder** [comment]
Forgot to mention 0 is space, new line and 0
* is * and math simbles. and # is case and T9 change.
* Please include it.
* Thanks in advance!

**Comment by sspanak** [comment]
@AgentGolder, I am trying to add the language, but the dictionaries I've found (including the one in Android OSP), contain letter variants with diacritics that you haven't noted above, such as: "ὐ", "ΰ", "ῆ", "ἦ", "ῷ" and many more. I am not sure if all of them are valid and in use today.

Could you please provide the full valid character list?

**Comment by AgentGolder** [comment]
You probably found the ancient greek. The only valid character today from those you mentioned is "ΰ".

**Comment by sspanak** [comment]
Ok, then what do with the words that contains such characters? Shall I replace with the respective with non-accented variants or throw the words away?

Here are some examples:
```
αὐτῷ
τοὺς
ἦν
οὐκ
ούσαν
κεφαλῆς
```

**Comment by AgentGolder** [comment]
You should replace them with the respective non-accented variants.

**Comment by sspanak** [comment]
Task completed! I tried typing some text in Greek, using a random Wikipedia article for reference and I think it is working very good. 

It will be officially available in the upcoming v23.0. Until then, if you are very eager to try it out, you could build an APK using the latest `master`.

**Comment by AgentGolder** [comment]
Thank you very much! You're very awsumn!
Can you please attach the .apk build for me here or send it to "agentgolder@gmail.com" somehow?
God bless you.

**Comment by sspanak** [comment]
Sorry, I don't have the capacity to make personal APKs. You will have to wait for the next stable release. Just keep an eye on [the releases page](https://github.com/sspanak/tt9/releases/).

**Comment by AgentGolder** [comment]
You can use a service such as sendspace.com, mediafire.com. Google drive, wetransfer, etc to upload the file on.
Thanks for your corporation.

**Comment by AgentGolder** [comment]
Hello.
Because I¨M totally blind )using a screen reading program= and don¨t have enough disc space for all Android studio¨s components to be downloaded, can you please upload an .apk file for me on one of the file hosting services above_
I¨ve already donated you 15 euros, more to follow soon.
Please understand that I really need it as soon as you can.
The problem is also that, I can¨t actually switch to Greek language when writing with the external bluetooth keyboard )Hoco S55 transparent).
Waiting for your responce, thanks and best regards.

**Comment by sspanak** [comment]
> Please understand that I really need it as soon as you can...

Please, understand this is a hobby project that I work on voluntarily, in my free time. There are no deadlines and no guarantees about anything and I would like it to stay that way. Hundreds of people are using this keyboard and they all want something. Even if I was working full-time on it, it wouldn't have been possible to grant everyone's wishes immediately.

The current state of the code is NOT ready for a public release. Once it is ready, I'll make an APK available to everyone. Please, have some more patience until then.

**Comment by sspanak** [comment]
@AgentGolder, v23.0 is out. Check it out [here](https://github.com/sspanak/tt9/releases/download/v23.0/tt9-v23.0.apk).

**Comment by AgentGolder** [comment]
Thank you very much for your understanding, you are a great person! I'll donate to support you again in the next days.

**Comment by sspanak** [comment]
You are welcome!
