### ISSUE TITLE
Cannot enter numbers when input is restricted to 123 mode

### ISSUE THREAD

**Issue by owen-young** [sspanak/tt9#290]
On a Kyocera Digno 903KC, when the input is limited to numbers only (i.e., input mode cannot be changed to abc/English), pressing number keys does not enter any information. When editing APN MMS port settings, for example, nothing can be entered. Video is attached. 

https://github.com/sspanak/tt9/assets/12684998/a6c67e17-4b3a-4192-b762-40cf365f60e2

**Comment by owen-young** [comment]
I also get this problem on certain apps when I switch to number mode, such as OsmAnd+ and Simple SMS. In the browser, I do not have this issue.

**Comment by sspanak** [comment]
This is the same as #241. I think we are very close to solving the problem. Please, follow the discussion there.
