### ISSUE TITLE
Add a "Delete Word" functionality

### ISSUE THREAD

**Issue by sspanak** [sspanak/tt9#298]
Provided that there is an "Add Word" function, users can add anything to the dictionary. However, if they make a mistake, they have no option of correcting it. To solve this, let's add a "Delete Word" functionality.

1. Add a "Delete Word" button on the "Languages" screen
2. Clicking on the button opens a new screen with a text field for entering the word and a "Delete" button
3. If no word matches the input, a toast message appears: "Word 'XXX' not found".
4. On success, the message is: "Word 'XXX' deleted successfully".
5. Make sure the new button becomes disabled when another dictionary operation is in progress. It may be a better idea passing the items to disable as an array, instead of one by one.

**Comment by TomJansen** [comment]
Wouldn't it be better to show a list with all the words that the user has added, and a search function to filter this list? Then, the user can select the words that it wants to be deleted

**Comment by coolgmr** [comment]
100% agree with TomJansen. This is exactly what I was thinking of.

**Comment by sspanak** [comment]
This will require a lot of work. Currently, there is no distinction between custom added and "factory" words. They are both stored in the same database table. When stepped in the project, I was thinking of separating them, but too many people started using TT9 too quickly, so I gave up the idea.

It is possible to migrate the custom words to a separate table, by reloading the `.csv` dictionary file and comparing it with the database, but this will require a lot of time and processing power... and battery. 

Besides, I don't feel like it is worth the effort. It is too much work, but the functionality would be almost the same: I want to delete a word, so I search for it, then press "delete". If I want this word gone, does it really matter if I added it or not?

**Comment by TomJansen** [comment]
I understand that it is a lot of work. But for the sake of the discussion, but in your proposed functionality, the user requires to guess how the word is spelled. Having a list of words is much more intuitive and the user can quickly see what word contains a mistake and no more guessing is required.

I sincerely appreciate the work that you have put in this app!

**Comment by sspanak** [comment]
So, what you suggest is just having the list of the custom words? If it's only them, I guess, it's OK to go with a list, instead of a search field. Still, I think at least the initial search will take a very long time, which may make the feature unusable on low end devices. 

I'll run some benchmarks on my 10-year-old tablet when I have time to confirm the idea would work.

**Comment by coolgmr** [comment]
I'm sure there must be a more straightforward way of doing this. Could you not just keep the "factory" words in 1 table & have a separate table for the custom words? Then, instead of merging the 2 tables together, make the predictive text use words from both tables. (Also then make it that users can only edit words on the "custom" table & add a search bar).

Really appreciate all your effort in this.

**Comment by maverick74** [comment]
My two cents on this:

One one hand: 
this could be like having another dictionary... a _user-made_ dictionary! Where we could add/edit/remove words.

one the other hand:
How many times do we actually use this? I've used touchpal for years now and have only 20-30 custom words. I thing i've removed/edited words one or two times in more than 10 years using it!!! I really think it does not worth too much effort put into it!

All in all:
If it's possible to implement it easily as kind of an independent dictionary, then that **would be the ideal**!!!
If it's too much work then, **at this point**, i don't believe it's worth it! We could take a simpler approach now and come back to this issue later on, if it reveals problematic...

i think it's really up to devs to analise the work needed :)
