### ISSUE TITLE
Change keyboard toggle

### ISSUE THREAD

**Issue by kpcenti** [sspanak/tt9#301]
Is there a way to toggle to different keyboard using the keyboard, like maybe through a hotkey?

I like to be able to easily toggle between tt9 and Google Keyboard. Holding the spacebar with Google Keyboard lets me go back to tt9 but no way to go back to google keyboard

**Comment by sspanak** [comment]
No, there is no such functionality at the moment. Android usually provides a way of changing the keyboard, either using a small keyboard icon in the lower right corner, or from the notifications panel, so I haven't considered adding such an option.

**Comment by kpcenti** [comment]
Is it possible to suggest this feature in the future? The OS version I have doesn't have a keyboard icon, and the notification panel is often cluttered. 

Pressing * brings up the app and the app already has a menu to change the keyboard. It would be a nice addition to have a hotkey pull up the change keyboard menu.
![Screenshot_20230712-182443](https://github.com/sspanak/tt9/assets/10696951/7d355e60-9b79-4d03-ba14-7aab0980c108)
![Screenshot_20230712-182451](https://github.com/sspanak/tt9/assets/10696951/b5192181-f5f9-4913-bc35-a9ca2442eeac)

**Comment by sspanak** [comment]
Yeah, I think this should be fairly easy to do.
