### ISSUE TITLE
Cursor placing not always works

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#320]
I'm experiencing a small problem: cursor placing doesn't always work.

For example, i type the text:

"_It's a rainy day_"

now i want to delete "_rainy_" and write "_sunny_". So i put the cursor in front of "_rainy_" and try to delete it.

the result is that sometimes it works as it's supposed too, but sometimes the cursor jumps to the end and **starts deleting "_day_" instead**...

**Comment by sspanak** [comment]
> sometimes the cursor jumps to the end and starts deleting "day" instead...

I think I know what you mean, but let's make it clear.
1. How do you "put" the cursor in front of "sunny"? Do you use a touchscreen or the arrow keys?
2. When you have moved the cursor, but before you have pressed Backspace, is the suggestion list still visible?

**Comment by maverick74** [comment]
>     1. How do you "put" the cursor in front of "sunny"? Do you use a touchscreen or the arrow keys?

I use the touch screen and tap in front of _rainy_
 
>     2. When you have moved the cursor, but before you have pressed Backspace, is the suggestion list still visible?

Yes! The suggestion is still visible for the last word typed: "_day_". 
now that you mentioned it, if i select the "day" word from the suggestion list or if i double space after it then i can already delete rainy with no problem.

(I would suggest that either we close this bug or you put it on your _very low priority_ list as it's just a question of knowing how to work-around the issue)

**Comment by sspanak** [comment]
This bug is bugging me as well sometimes, so let's fix it. In the meantime, you could indeed use "space" or "OK" to accept the current suggestion and then move the cursor.
