### ISSUE TITLE
Bugs found in v24

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#338]
First of all: v24 is a massive improvement in terms of GUI!!! Its an amazing update, however I think I found 3 bugs:

1. When I filter a word, how do I clear the filter? Clear button is gone (and shortcut keys ain't working)!

2. I type non-existent word and place the cursor after it!; I press + to add the new word; Now try to edit the word! (in my case, as soon as I try to edit it, the input window goes away!)

3. Back button cannot be used to hide the keyboard (ok! This is not from v24. It happen before... but I think we need a way to hide the on-screen keyboard if we need it)

**Comment by maverick74** [comment]
Regarding 3.: its funny because I restored the default shortcuts and now, when I press the back key it behaves as I was expecting it to

one tap on back hides the keyboard, a second tap makes the app go back!!!

(I don't know if this is expected, but I like it!)

**Comment by sspanak** [comment]
Regarding 3, TT9's primary audience are non-touchscreen phones, so the default key setting may not be perfectly suitable on your phone. Check out [the manual](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#on-screen-keypad) for more info. Resetting the default settings has different effect when the On-screen keyboard is enabled and when it's disabled, so what you did adjusted the keys for best experience on your phone.

> oh and this solved https://github.com/sspanak/tt9/issues/336 !!! - so, if its working as it should be, you can close the other bug!!!

Thanks for reporting, but please, do not mix the issues like this. Comments regarding #336 must go in #336.

**Comment by maverick74** [comment]
Yes it does answer! Thank you!

Regarding 2.: the popup window is going away, but will we get another (better) way to add/edit (maybe even remove...) words?

**Comment by sspanak** [comment]
It will be the same, just a bit simpler. You'll see.

As for removing words, I had an idea of adding a new screen accessible from Settings -> Languages, with a search field, that would allow you to search for any word and delete it by clicking/tapping on it. There is an issue for that, #298 and I would have already done it, but a discussion started and we couldn't agree to a single solution, so I gave it up for now. If you feel like it, join the discussion.

**Comment by maverick74** [comment]
unless you want to keep this open until 1 and 2 are out, for me you can close this (for the sake of github issue's list cleanness)!

1. is getting back
2. is going to be solved
3. It's invalid
