### ISSUE TITLE
Keypad registers two presses when only pressing once.

### ISSUE THREAD

**Issue by skipback** [sspanak/tt9#342]
Sometimes when using predictive text, pressing a key once will type two letters, this could be a hardware issue on my end although I haven't encountered it anywhere other than typing.

The keyboard also sometimes adds a number when I start typing, in addition to the letter I have selected.

Thanks for all of your hard work on this incredibly useful tool!

**Comment by sspanak** [comment]
Yes, it sounds to me that some system key handler occasionally kicks in and tries to type numbers and whatnot. I suppose your phone is running a heavily customized version of Android, like Kyocera and LG, which is really difficult to deal with. Unfortunately, I don't think anything can be done, besides going back to your default keyboard, as **alexknop** suggested.

Out of curiosity, what is your phone make and model?
