### ISSUE TITLE
Add an ability to type punctuation marks and symbols in Mode123

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#345]
Some text fields only allow Mode123 because of their input types. If you want to type decimal, you don’t have the option to put the  period. Other symbols are also unavailable. And you can’t change Mode123 to others to access the characters under numbers 1 or 0. It would be nice to have an access to the symbols in Mode123.

**Comment by sspanak** [comment]
I was thinking about this. This is a bit tricky, because, for example, my phone doesn't have extra keys that could be used for displaying the special characters. Probably, holding 0 and 1 to display the usual list of punctuation/math characters would work out fine. What do you think?

**Comment by qascot** [comment]
I think that holding 0 should type “+” because that's what anyone expects to get in this case. Other action may affect mode dialer. Perhaps, while holding down the 1 key, the characters should be displayed, and the next time you press 1, new ones will appear.  Just as it is done with the emoticons in prediction mode. 
Another option is that holding 0 should show candidate characters with + in first place.

**Comment by sspanak** [comment]
> Another option is that holding 0 should show candidate characters with “+” in first place. In this case it would be helpful if the following presses 1 and 0 will scroll through the suggestion list to select the desired symbol. And, of course, an auto accept would be very convenient.

I like this option better. I think it would be confusing if sometimes the special characters appear on 0-key, but sometimes on 1-key. I already see complaints coming in... It's easy to put "+" at the beginning and enable auto accept.

**Comment by qascot** [comment]
You're right. The same actions should lead to the same results. Although a long press is different from a single press, but the buttons are the same. And it is logical for the user to try a long press on the button that he used to enter characters in other input modes.

**Comment by stianhoiland** [comment]
This sounds like an awesome feature. Long-pressing 1 and 0 in 123-mode to bring up punctuation and symbols, with the caveat that the symbol list starts with "+" as expected.
