### ISSUE TITLE
More intuitive key remapping

### ISSUE THREAD

**Issue by sspanak** [sspanak/tt9#35]
The current way of key remapping puts too much power in the hands of the user and requires too much technical knowledge and reading the Android documentation to figure out the key codes. Also, it makes no sense to remap the number keys, because the norm for them is to type letters. So:

- ~~Add a "Special Function Keys" section in the preferences.~~
- ~~Allow remapping of functions only, not keys.~~
- ~~Display a list of functions ("Backspace", "Next Input Mode", "Show Settings" and so on)~~
- ~~Next to each function it is possible to select a key `*`, `#` or `CALL` along with hold option. All phones have these three keys, so using them only should be safe enough.~~
- ~~Validate conflicting selection of keys.~~
- ~~Consider adding other useful keys, such as BACK, DELETE, the LEFT MENU KEY, F1, F2 and so on.~~
- ~~It is possible to select no key for a function.~~
- ~~Ensure default settings on initial startup.~~
- ~~Update the user manual.~~

After #14, #29.

**Comment by puffertron** [comment]
Hey, I was wondering how key remapping currently works, I haven't found where to put the "keymap.txt" file. I'm very thankful for your work on restoring this app btw :) thanks so much!

**Comment by sspanak** [comment]
There is no `keymap.txt` file anymore. The entire app works very differently, so please only refer to the [user manual in this repo](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md)

The old way using the text file seemed overcomplicated and required knowledge about how Android interprets key presses, so I decided to ditch it.

Currently, the only way to change the keys is by manipulating the code. I do intend to add a keymap section on the Settings screen, though. That's what this issue is for.
