### ISSUE TITLE
Android 4.4.2 After the input is completed, the candidate box at the bottom cannot disappear in other interfaces, such as launcher

### ISSUE THREAD

**Issue by gleaner-m** [sspanak/tt9#351]

**Comment by sspanak** [comment]
This is definitely not a general problem on Android 4.4.2. I have a tablet with the same Android version and I don't have this problem. It must be something specific to your device.

Anyway, please try the latest v26.0. I have fixed a couple of crash scenarios, which may have contributed to your problem.

**Comment by gleaner-m** [comment]
Yes Android 4.4.2 is a very old version, I guess I don't know the specific brand of the device

**Comment by sspanak** [comment]
@gleaner-m, please try out the new [v27.0](https://github.com/sspanak/tt9/releases/tag/v27.0). It fixes a similar bug on other devices, so it may help in your case too.
