### ISSUE TITLE
Add an option to completely hide the interface

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#354]
The option to hide soft buttons is very useful for phones with small screens. But what if we take the next step and add the option to hide candidate list? Of course, this can cause uncertainty to inexperienced users. But experienced T9 users will be able to focus on the text being typed without being involuntarily distracted by the list of candidates. Anyway, the candidates change sequentially one after another and there is no way to select an item from the middle of the list. Thus, scrolling  through the list, even if it is not displayed on the screen, will lead us to the necessary candidate. 
If the interface is completely hidden, the entire small screen will be accessible to the active application. Eye movement will decrease, vision fatigue will decrease. The printing speed may increase. 
But it's uncomfortable to choose symbols and emoticons blindly. Their candidates must be shown by clicking on 1 or 0. And hidden again when the input confirmed.
Also, with this option, the input mode and language should return to the status bar.
I’ve tried to do this and was satisfied with how convenient it is.

**Comment by DarthFlip** [comment]
> I have this implemented in my own little fork.

Would you be able to share your fork? Or maybe try getting it merged back to this app. I would love such a feature.

**Comment by sspanak** [comment]
I agree about everything, except the status bar icons. They are difficult to maintain and complicate the procedure of adding a new language. Besides, I could never make them look properly on any device I own. This are not coming back, sorry.

Other than that, I also think it sounds cool and it would be a nice addition to TT9. Maybe, just under a different name, not "toast mode". :smile: I was thinking of maybe changing the "on-screen keys" setting to a dropdown with three options: "hidden", "minimal", "numpad" or something like that. The summaries of the current two on/off options could even be reused and we only have to come up with one for the "hidden" or "off" mode. I believe it would work out well.

**Comment by stianhoiland** [comment]
I lied.

I don't have this implemented, only spec'ed and planned.

I'm ashamed.

Lately I've compiled a lot of personal notes on features and fixes for tt9 which I hope to contribute to the project, and I got ahead of myself and too carried away while replying to this issue—I think because I wanted to show off. I regret that.

I have messaged Dimo directly and apologized to him personally.

I hope you accept my apology.

Sorry.

**Comment by sspanak** [comment]
That's OK, man, there is nothing to worry about. If you don't know how to write the code for this feature, that's fine. No one should have any hard expectations about anything. It's a hobby project after all! I don't fulfil all the requests I get either, for one reason or another. And that's fine too.

Just take it easy. Don't worry and be happy! :partying_face:

Btw, I get absolutely no notifications from strangers in Messenger, so I have missed your message. Sorry about that!

**Comment by stianhoiland** [comment]
Thanks for your reply, and to be clear I'm not sorry that I haven't implemented the feature request, I'm sorry that I outright lied about having done so. I'll be more mindful of myself, and thanks for easing my conscience.
