### ISSUE TITLE
Currency symbols

### ISSUE THREAD

**Issue by pachpict** [sspanak/tt9#370]
Phone: Cat S22 Flip.

I cannot find any way of typing £ or €, or any other currency symbol for that matter. Am I missing something obvious? It seems an unlikely oversight; the keyboard isn't practical without currency signs.

I have read the manual, the README and tried every button combination I could think of.

Thanks

Ed

**Comment by sspanak** [comment]
> Am I missing something obvious?

You are not missing anything. As of now, the only supported special characters are the ones you see when you press 0-key or 1-key, and the currency symbols are not among them.

> the keyboard isn't practical without currency signs.

Whether this is practical or not, depends on one's needs, right? :slightly_smiling_face:  I mostly use the phone to chat with my friends and I really can't remember when was the last time I needed to type a currency sign. Nevertheless, some people would definitely need currency signs, if not in everyday messaging, maybe just for typing passwords. So I agree it is worth adding them.

I was thinking of a way of adding support for more special characters and I would probably go for 0+another key combinations. For example, "01" would yield various currency signs and "02", "03", ... would be reserved for future needs. How does the idea sound to you?

**Comment by pachpict** [comment]
I think you've got a good idea: Another mappable shortcut key that has a fuller range of special characters would be very handy. Imd suggest going the whole hog and have it scroll through a full range of an extended character set in order, as opposed to a custom list. For maximalism you could use the full Unicode character set. Or the full Windows-1252 character set if we aren't going OTT.

After writing the issue I messed around more and was sure I hadn't missed anything. I assumed you were going to suggest I write a custom International English language and submit it. I'm glad you're thinking of a more widely applicable solution. Much appreciated.

**Comment by maverick74** [comment]
considering your last note: how about using a long press on keys "?" or "!"  (or something...) to access the extra characters?

(just an idea...)

**Comment by sspanak** [comment]
> considering your last note: how about using a long press on keys "?" or "!" (or something...) to access the extra characters?

Only if phones had such hardware keys...

![cats22](https://github.com/sspanak/tt9/assets/27846105/bc56a487-332e-4dc7-a1b4-fa1dafbc1efe)

**Comment by maverick74** [comment]
question: How can i get into this with the on-screen keyboard? (i'm doing something wrong for sure...)

**Comment by sspanak** [comment]
The same way you would do with hardware keys - press 0, press the Next Typing Mode key (the one with the keyboard on it). It's the same as changing the special characters to uppercase, but since they can't be in uppercase, the next character group is displayed.

**Comment by maverick74** [comment]
Oh! I see!

Because, above, its mentioned 0+# I was not getting it!

Working great!!!

Thanks
