### ISSUE TITLE
Shortcut to voice dictation? 
Maybe Something like Google's voice access. 

### ISSUE THREAD

**Issue by Pbeight** [sspanak/tt9#371]
I use voice dictation a lot , and I'm currently using voice access on the F21 Pro.
 However, I have no way of mapping a physical key to turn on voice access so I need to constantly open notifications in order to activate it.
 I'm wondering if there's some way for you to make a shortcut within your keyboard app so that the top left smiley face key would be able to toggle it as part of your app. 

Alternatively, - and I don't know much about this so I don't know if it's feasible - maybe voice dictation can be implemented without using the voice access app at all? 

Once again I absolutely love your app this phone would be really hard to use without your App, to put it mildly. 

Thank you so much!

**Comment by sspanak** [comment]
> Alternatively, - and I don't know much about this so I don't know if it's feasible - maybe voice dictation can be implemented without using the voice access app at all?

There has been requested an year ago, but I never had time to implement it. I am still willing to do it though. It is definitely going to be useful.

Please follow #83 for updates.

> this phone would be really hard to use without your App, to put it mildly

I agree completely! These days such phones seem to be designed by people who never use or have never used them in their life.

> Thank you so much!

You are welcome! Enjoy and spread the word if you will.
