### ISSUE TITLE
Requires Vietnamese input language

### ISSUE THREAD

**Issue by Phalam754** [sspanak/tt9#372]
I need to add Vietnamese input method VI. Vietnamese import dictionary may not be needed.  I have a Vietnamese typing app for you to see. Punctuation marks are typed with key 1.
https://drive.google.com/file/d/1yBfrpMpizhSfAQ5y6pMsgShTPJBxLBBg/view?usp=share_link
Sorry I used google translate

**Comment by sspanak** [comment]
Adding Vietnamese is certainly possible, but:

1. TT9's main goal is to provide Nokia experience on Android devices, so it will definitely not mimic the behavior of the app you are using right now. In other words, there will be no key combinations for typing diacritics (if that's what you meant). For example, 2-key will type all variants of "A".
2. Currently, I have very little free time, so I can't promise I'll add new languages anytime soon.

**Comment by Phalam754** [comment]
Thank you for your feedback 
I'm using a modded t9 keyboard.With Vietnamese input method added. qinpad application is modded by Vietnamese people. The interfaces are too old and have stopped updating.
Link Qinpad mod Vietnam https://drive.google.com/file/d/1yBfrpMpizhSfAQ5y6pMsgShTPJBxLBBg/view?usp=share_link
Hold down the # key to switch to Vietnamese input method 
Press key 1 to add accents to letters. Vd: À Á Ả Ã Ạ
Press * key to delete.I don't like this because it's different from Nokia. Your t9 application is the back key, This is great.
Can I contact you through another channel? Telegram or discord

**Comment by sspanak** [comment]
> Press key 1 to add accents to letters. Vd: À Á Ả Ã Ạ
Press * key to delete.I don't like this because it's different from Nokia. Your t9 application is the back key, This is great.

So we are on the same page and it's all good!

> Can I contact you through another channel? Telegram or discord

I'd rather keep all information and discussions in one place and publicly available here, in Github.

**Comment by Phalam754** [comment]
> Tôi muốn giữ tất cả thông tin và thảo luận ở một nơi và công khai ở đây, trên Github.

Can you help me move the delete function from the * key to the back key? The application I submitted above.
Thank you very much

**Comment by sspanak** [comment]
No, sorry, I can not provide support for an application created by someone else.
