### ISSUE TITLE
Upgrade Cyrillic languages dictionaries

### ISSUE THREAD

**Issue by sspanak** [sspanak/tt9#373]
- Upgrade Russian. Use the words from the 4PDA dictionary. Filter any repeating and nonsense words.
- ~~Upgrade Ukrainian. Use the words from AOSP.~~
- ~~Upgrade Bulgarian.~~

**Comment by jaggedjimmyj** [comment]
Currently the Russian dictionary is barely usable, because of the lack of cases for words. Are you planning to fix that in the scope of this issue, or should I create another one?

**Comment by sspanak** [comment]
Yes, I got the large dictionary, containing ~1500000 words, which has been circulating the 4PDA forums, and also the Android spell checker dictionary containing ~220k words. They contain some repeating words and nonsense, such as "АААА" and "ББББ", so I intend to clean them up and merge them. After that, I believe Russian will actually become usable.
