### ISSUE TITLE
Improve ease of use for ABC mode

### ISSUE THREAD

**Issue by yetimoose** [sspanak/tt9#378]
Hiya!

Using a CAT S22 flip. When typing in ABC mode, if I am typing a word where there are two or more consecutive letters under the same number (Cat for example, both C and A are on 2, so it's 222-2-8, or Mood 6-666-666-3) the only way I seem to be able to move on to the next letter is by pressing the middle/OK button on the keypad. I wish it would just determine that I'm done with the current letter after a pause in typing so I could press the same number and have it type a new letter/number after cycling through again. It's something I liked about another T9 app I used, however I do prefer this one generally.

Another thing, I wish there was a shortcut to toggle between this keyboard and other enabled keyboards on my phone. I'm not sure if this has more to do with the phone than the app but I thought it was worth a shot to mention it. I like typing with this keyboard but for passwords and emails I usually would rather switch to an on screen QWERTY keyboard but it's very annoying to go into settings every time.

Thanks for this amazing app though!
Megan

**Comment by sspanak** [comment]
> Using a CAT S22 flip. When typing in ABC mode, if I am typing a word where there are two or more consecutive letters under the same number (Cat for example, both C and A are on 2, so it's 222-2-8, or Mood 6-666-666-3) the only way I seem to be able to move on to the next letter is by pressing the middle/OK button on the keypad. I wish it would just determine that I'm done with the current letter after a pause in typing so I could press the same number and have it type a new letter/number after cycling through again. It's something I liked about another T9 app I used, however I do prefer this one generally.

Go to Settings -> KeyPad -> ABC Mode (at the bottom), then enable auto-accepting. It is supposed to be on by default, but it may be off for one reason or another.

> Another thing, I wish there was a shortcut to toggle between this keyboard and other enabled keyboards on my phone. I'm not sure if this has more to do with the phone than the app but I thought it was worth a shot to mention it. I like typing with this keyboard but for passwords and emails I usually would rather switch to an on screen QWERTY keyboard but it's very annoying to go into settings every time.

Go to Settings -> KeyPad -> Hotkeys and select a key for the "Next Keyboard" function. You may have to unassign something else if your phone has too few available buttons. This function is disabled by default, because, for example, my phone has only 3 keys the could be used for special functions and it is simply not possible to enable them all.

> Thanks for this amazing app though!
Enjoy! :slightly_smiling_face:

**Comment by yetimoose** [comment]
![Screenshot_20231004-144303](https://github.com/sspanak/tt9/assets/146888011/123c2723-6517-4933-a65f-e2fc2ece95f7)
![Screenshot_20231004-144246](https://github.com/sspanak/tt9/assets/146888011/5e521f55-5e38-4a62-a3d6-277d579b2b14)

Ok awesome that these are already features but there's the problem.. Both those options in settings don't exist for me. There is no ABC Mode section in settings only Predictive Text and I see no way of toggling to a different mode. Also see the screenshot of Hot Key options, the only other option is Reset to Default which is not shown in the screenshot but no Next Keyboard function. I can do a screen recording of all the sections in my settings if you want to see but it must just be a problem with the app specifically on my phone or the CAT S22 in general. Not sure, hopefully it's just a mistake I'm making or something I don't see.

Thank you for such a quick response!!

**Comment by sspanak** [comment]
Oh, you must be using an old version. Please install [v26.0](https://github.com/sspanak/tt9/releases/tag/v26.0) and the settings in question should appear.

> it must just be a problem with the app specifically on my phone or the CAT S22 in general

There are no restrictions by device, all functionality is available on all phones. There may be some glictches on very old ones with Android<5.1, but other than that everything should work and look the same for all.

**Comment by yetimoose** [comment]
Ah! I absolutely was, I had v21.0 oops... Thank you!!

**Comment by sspanak** [comment]
If you had v21.0 before, then you also need to re-load the dictionaries for all languages you are using, otherwise some common words will be missing in Predictive mode.
