### ISSUE TITLE
Automatically load dictionary on initial use

### ISSUE THREAD

**Issue by AndroFlipper** [sspanak/tt9#381]
Hi, thanks for this amazing project.

I think it would be very useful if we can get the Dictionary automatically loaded on initial use.

While I am not too good in Java development, I would think the easiest unprofessional way would be as follows:

1. When IME detects there are no words in the database (which currently triggers a toast notification), it should temporarily set a boolean noDict=true
2. Thereafter, it should open the Settings page
3. On starting the Settings page, it checks noDict's value, if true, then [open the Languages section, and] set noDict=false & trigger Load dictionary.

@sspanak Please let me know your thoughts, and once again, thanks very much for all your work!

**Comment by sspanak** [comment]
Well, this is a very roundabout way of loading the dictionaries, while it's just a matter of calling `DictionaryLoader.load()` with an `ArrayList` of the currently enabled languages. I would certainly not try to do it as an automated test. :slightly_smiling_face: 

Anyway, given that loading could take minutes on slower phones, I am not sure it is a good idea. I'd rather let the users choose when to run such a heavy operation as opposed to doing it automatically.

**Comment by lgexalter** [comment]
I think this is a great idea and would love to implement it. I don't think it would be such a heavy operation if you just load one language automatically (e.g. English- since a nice amount of people would be using English).

**Comment by sspanak** [comment]
I guess the most optimal solution would be to do it only once, after installation/update. After that, dictionary management is up to the user. I see no reason to reload anything automatically.

>  I don't think it would be such a heavy operation if you just load one language automatically (e.g. English- since a nice amount of people would be using English).

I'd rather reload whatever is currently selected or detected the phone language and default to that.
