### ISSUE TITLE
Occasional hide of a letter

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#386]
Occasionally, I'm experiencing a weird behavior:

when I type the word "como" (like / eat in Portuguese)

it sometimes hides the last "o" rendering the word as "com" even when I'm sure to type 4 letters!

However, most of the times the word is rendered correctly!!!

**Comment by sspanak** [comment]
This is a known issue. It happens because sometimes searching in the word database takes too much time, which messes up the word list. It will be fixed in #366

**Comment by maverick74** [comment]
Ok! I'll close it then! Makes on sense in having a duplicate open! Thank you!
