### ISSUE TITLE
Is it possible to make OK send messages in telegramm?

### ISSUE THREAD

**Issue by Mishafuse** [sspanak/tt9#392]
Hi! Is it possible to make OK send messages in telegram like you did in Facebook messenger?
Thats would be very usefull :)

**Comment by sspanak** [comment]
Hi! It is actually a setting in Telegram. Go to Settings -> Chat Settings -> Other Settings and Enable "Send with Enter". 

The messaging programs are supposed to do it on their own, but in Facebook they've decided to take away the option. This is why added this special hack.

**Comment by Mishafuse** [comment]
Wow, huge thanks and respect!
