### ISSUE TITLE
Hungarian (UTF16) language

### ISSUE THREAD

**Issue by Milan9889** [sspanak/tt9#395]
Love this app, it helped much with my f21 pro.

I couldn't find a way to add Hungarian dictionary with ö,ő,ó,í,ü,ű,ú.

Please help me with adding the language, or helping me to do so

Thanks!

**Comment by sspanak** [comment]
I believe Hungarian fits completely in UTF-8, while UTF-16 is for East Asian languages, so I am not sure why you mentioned it.

Either way, adding it is certainly possible. I'll try to release it in one of the upcoming versions.

**Comment by Milan9889** [comment]
Hi! I might be wrong, but Í, Ű, Ő are UTF16. If You plan to add Hungarian, I can provide dictionaries.

**Comment by sspanak** [comment]
> I might be wrong, but Í, Ű, Ő are UTF16

They fit in UTF-8, too. Don't worry about it.

> If You plan to add Hungarian, I can provide dictionaries.

That would be great. I am going to use the Android OSP dictionary as a base, but I can see it contains only 66000 words. Knowing that Hungarian has a lot of grammatical cases, 66k is definitely not enough for providing good predictions.
