### ISSUE TITLE
I made czech into TT9... probbably

### ISSUE THREAD

**Issue by peebee-eu** [sspanak/tt9#396]
Hey I don't know if this is enough, I just got my CAT S22 Flip, and want to type in czech, so I did this whole dictionary programing jig. Its not a .csv but .txt I hope thats enough. Cheers
[CZ.zip](https://github.com/sspanak/tt9/files/13467768/CZ.zip)

**Comment by sspanak** [comment]
Nice! There is already an open pull request about Czech: #380, but it looks like there very few words included. This word list looks much better. I'll try in one of the upcoming versions.

**Comment by sspanak** [comment]
@peebee-eu, could you also provide a link to the source where you got the word list?
