### ISSUE TITLE
Hold Back Button to Delete One Whole Word 

### ISSUE THREAD

**Issue by theancientways** [sspanak/tt9#408]
Hello, I'm on a Sonim XP3Plus dumbphone w/ physical keypad. Right now if a word comes out mistyped and I want to erase it and retype, I have to hold the back button and wait for it to delete one character at a time. This can get a little time consuming with frequent mistyped words. It would be great if there could be an option to delete one whole word at a time by holding the back button which can be toggled on or off in the app settings. 

Thanks as always.

## Upvote & Fund

- The repository is using [Polar.sh](https://polar.sh/ddimo) so you can upvote and help fund this issue.
- The funding is received once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund the backlog.

<a href="https://polar.sh/sspanak/tt9/issues/408">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/sspanak/tt9/issues/408/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/sspanak/tt9/issues/408/pledge.svg">
</picture>
</a>

**Comment by sspanak** [comment]
Short asnwer: I can certainly add such an option and it will work, provided that you don't use the combined Back/Backspace key.

Long answer: this is not possible with the Back button. Android does not permit assigning any functions to the hold event. I tried to do it in the past, but either I can not figure it out, or it is not possible at all. This is just fyi.

However, it is possible when the Backspace function is assigned to any other button. You probably have a Backspace or a DEL button, not a Back button. The former would erase text when held, while the latter would perform some system function, such as display the list of all running apps or kill the current app.

So, it is possible, with one small exception.
