### ISSUE TITLE
Missed Keypresses When Typing Quickly

### ISSUE THREAD

**Issue by theancientways** [sspanak/tt9#409]
Sonim XP3plus dumbphone w/ physical keypad. I'm experiencing an issue when typing fast where TT9 will miss keypresses, about one per word. For example the word "going" comes out "imho" because it missed one of the keypresses. At first I thought it was a problem with my phone's keypad but this issue doesn't happen when using the phone's native text input method KT9.

Thanks as always.

**Comment by sspanak** [comment]
This is a duplicate of #366. The bug is fixed in the `master` branch, but it has not been released yet. It should be out by the end of January.

**Comment by theancientways** [comment]
Thanks for letting me know, it certainly is the same issue.

**Comment by sspanak** [comment]
@theancientways, [v27.0](https://github.com/sspanak/tt9/releases/tag/v27.0) is out. It should eliminate typing lag issues you have been experiencing.
