### ISSUE TITLE
Support for compound words in predictive mode

### ISSUE THREAD

**Issue by mathlu** [sspanak/tt9#418]
In swedish, and possibly other languages compound words exist where words consist of two or more words joined together. For example the word for fever thermometer in swedish is "febertermometer" consisting of the word "feber" for fever and "termometer" for  thermometer. 

Since it would not be feasible to add all possible combinations of words that make up these compound words to the dictionary it would be good to be able to mark that input has finished for one part of the word and that a new word is starting without a space being added in predictive mode.

Suggested flow:
* Enter first part of word 'feber'
* Press d-pad "Down" to mark that the first part of the compound word is finished
* Enter last part of word 'termometer'
* Press "OK" or 0 for space
* Enjoy your beautiful new compound word and possibly press * to add it to the dictionary if used often.

References:
http://nds2.webapps.microsoft.com/files/support/apac/phones/guides/Nokia_5210_APAC_UG_en.pdf page 20.

**Comment by sspanak** [comment]
Well, you can type compound words even now. Just type the first word, hit backspace to erase the extra space and type the second word. 

Or, if you don't want automatic spaces added, just turn them off from Settings -> Keypad -> Predictive Mode section -> Automatic Space. This way, OK will not add an extra space and you would be able to choose whether to add one with 0-key or not.

Now, if you still want automatic spaces only after punctuation, it is possible to split the setting and have something like "Automatic space after words" and "Automatic space after punctuation". This way, you would have even finer control. And... I think it's the best I can do. You can't have auto correction on and off at the same time... :slightly_smiling_face: 

Finally, TT9 recreates the Nokia experience on modern Android devices, but it is never going to be _exactly_ the same as Nokia 5210 or 3310 or any other. You can't expect that. It will always be somewhat different from your past favorite phone.
