### ISSUE TITLE
Increase size of keyboard and import contact names, company names from phonebook/contact list...

### ISSUE THREAD

**Issue by davidequiz** [sspanak/tt9#419]
Good afternoon,

The keyboard works very well... but, this options could be great improvement...

Many thanks in advance...

**Comment by sspanak** [comment]
I am not sure about the first part of your request. Does it appear to small on your phone? Could you provide screenshots? I have tested it on different sized screens from 2.8" to 6.2" and made sure it is large enough, without taking up too much screen space and covering the applications. From my perspective, it looks quite good.

Please, clarify what is wrong.

As for the second part, including contact names is going to be tricky. Each language in TT9 has only a limited character set. This is both good for performance and for keeping the code simple. Adding just any word would mean it may contain a special character or an unsupported letter, which will make TT9 crash. And this unacceptable.

All in all, contacts can not be added, sorry! You'll have to do it manually.
