### ISSUE TITLE
Sonim xp3900 -Traditional T9 couldn't be installed on your phone

### ISSUE THREAD

**Issue by asherGe** [sspanak/tt9#429]
Hi, Wondering if this should work on 12-key flip phones like the Sonim xp3900 (xp3Plus)? When I try to install the downloaded package I get the response: App not installed. Traditional T9 couldn't be installed on your phone. This phone is running Android 11. The predictive texting that comes with this phone is driving me crazy and was hoping your app here would give some relief!

**Comment by sspanak** [comment]
There may be a couple of reasons for that:

Have you installed another an older version of Traditional T9? If yes, you may have to uninstall it and try again.

Are you able to install any other APKs? There is no special procedure for installing Traditional T9, so if you can install other apps, you should be able to install it, too. 

By default, Android forbids installing anything, to protect you from viruses and malware. You will have to find how to disable this setting on your phone, so that you can install custom APKs. Have in mind, some phones are just locked and there is no such setting. There are tricks to use the backup function with an SD card, but I am not familiar with how this works. You will have to do a research on your phone.

**Comment by asherGe** [comment]
Sspanak, thanks for your response. Good news, I got it to install!

Older version not installed. I knew apps could be installed because I have iMobie DroidKit that is an application I installed on my laptop that  walks you through connecting to your phone via USB cable (requires enabling Developer Options, USB debugging ON, and USB Default Configuration - File transfer). 

I did some searching and found out about app.webadb.com. I got app.webadb.com to connect to the phone via USB cable and was able to install Traditional T9 using the Install APK tool on webadb! It is working fine on the phone! I'm working through the setup and just read through your manual again.  I am learning how to use it pretty quickly.  I cut my teeth on texting with a 2005 vintage LG flip phone (2G) that I used up until around 2020 when Verizon forced me to upgrade to 4G-LTE. This is AWESOME! I LOVE IT! 

Questions not clear from the manual:
On my phone it is not displaying the predictive word list or the current keypad entry mode. I can get used to this but just wondering if I am missing something. Is there a way to get it to display: 1) the predictive word list 2) which keypad entry mode I am in?
Is there a way to get these special characters: "(" or ")"  ?  I saw the thread on currency characters and assume it is same response for this?

**Comment by asherGe** [comment]
Regarding my questions - I just discovered if I press OK (center direction button) before starting to type anything then the word list and current keypad entry modes show up in the display! Great. And I see the "(", and ")" special characters are there... Is this the way it is supposed to work?

**Comment by sspanak** [comment]
Yes, OK is used to fully activate Traditional T9 when it is invisible. It works as intended.

At the beginning, it used to force show itself, but then it wouldn't hide when it had to. In fact, on some phones it remained visible forever, which is again undesirable. In the end, I've decided to go with this solution balanced between user control and causing annoyance automatically.

I am making a note to add that OK can be used to show the UI when it is invisible.

Also, have in mind Kyocera and Sonim customize Android quite a lot, which makes it difficult to support. You may notice TT9 does not work as good as the native keyboard when it comes to some specific functionality, for example sending messages with OK (it may not work in all apps), or you may have issues with search fields. Or it may be just fine, I don't know. Every phone is different.

**Comment by theancientways** [comment]
I'm on the Sonim XP3plus as well and TT9 is miles ahead of their lazily programmed stock text input which is racked with bugs that make it virtually unusable. Sspanak is a legend.
