### ISSUE TITLE
In numeric fields it is impossible to type a comma or a period on Qin f21pro

### ISSUE THREAD

**Issue by qascot** [sspanak/tt9#446]
For example, in banking apps entering the amount. Usually, in these text fields, the on-screen keyboard is displayed in the form of numbers, a comma and a period and several function buttons (space, enter, backspace). Using TT9 there is no way to type a comma or a period into this field, because long pressing on 1 or 0 does nothing.

**Comment by qascot** [comment]
Is it possible that the problem is related to the #369?

**Comment by sspanak** [comment]
#369 is so weird that I cannot say what could be the side effects of a missing icon. It doesn't look related, but it might be.

Now let's go back to the problem itself. First, I don't think this it is specific to Qin F21 Pro. Banking apps and apps with numeric input fields sometimes do modify what you type to prevent invalid numbers. And sometimes, they refuse to take composing text (the underlined temporary text, displayed before you select a suggestion). I believe this is causing the problem

I am gonna have to find a way of detecting such numeric fields and displaying only the suggestion list, but not the composing text. Hopefully, this way it will be possible to select all characters on 1-key or 0-key, even if some of them may be discarded by the app. For example, the banking app will likely reject "&" when entering an amount.
