### ISSUE TITLE
Are there any Recommended External Dialpads/Numpads?

### ISSUE THREAD

**Issue by ForrestHerman** [sspanak/tt9#449]
Is anyone aware of an external Bluetooth numpad that would be good to pair with this? Specifically one that is more in the form factor of traditional flip phones and other phones with numpads. All of the devices I am aware of are more like keyboard numpads and are not suitable for holding in one hand and thumb typing like it possible on a traditional phone numpad.

**Comment by theancientways** [comment]
Interesting question. [There are a bunch on amazon](https://www.amazon.com/s?k=bluetooth+number+pad&i=electronics&crid=S6G1T0FOKWWE&sprefix=bluetooth+number+%2Celectronics%2C244&ref=nb_sb_noss_2):

**Comment by ForrestHerman** [comment]
> Interesting question. [There are a bunch on amazon](https://www.amazon.com/s?k=bluetooth+number+pad&i=electronics&crid=S6G1T0FOKWWE&sprefix=bluetooth+number+%2Celectronics%2C244&ref=nb_sb_noss_2).
> Some of them look small enough to hold in the hand like a phone keypad.
> 

I looked at a lot of those and unfortunately there are a couple of issues with all of the ones I am seeing related to muscle memory and hand size. 

The biggest issue is the layout. Keyboard number pads are reversed from phone number pads (top row on keyboard number pad is 7 8 9, where as a phone number pad is 1 2 3). Even if that were not the case, even the smallest ones seem to be a bit too large to type the exact same way I do on a dumb phone. 

If I am being daft and just missing something obvious in terms of a product that is about the right size and layout, feel free to let me know.

**Comment by theancientways** [comment]
> > Interesting question. [There are a bunch on amazon](https://www.amazon.com/s?k=bluetooth+number+pad&i=electronics&crid=S6G1T0FOKWWE&sprefix=bluetooth+number+%2Celectronics%2C244&ref=nb_sb_noss_2).
> > Some of them look small enough to hold in the hand like a phone keypad.
> 
> I looked at a lot of those and unfortunately there are a couple of issues with all of the ones I am seeing related to muscle memory and hand size.
> 
> The biggest issue is the layout. Keyboard number pads are reversed from phone number pads (top row on keyboard number pad is 7 8 9, where as a phone number pad is 1 2 3). Even if that were not the case, even the smallest ones seem to be a bit too large to type the exact same way I do on a dumb phone.
> 
> If I am being daft and just missing something obvious in terms of a product that is about the right size and layout, feel free to let me know.

I see what you mean. Is your intention to pair this with a smartphone to be able to type as if using a flip phone? If so there are small bluetooth keypads like [this one](https://www.amazon.com/Rii-Bluetooth-Rechargeable-Handhelds-PS3-BLACK/dp/B0B46F8RS6/ref=sr_1_1?crid=3VJ7GFHFP81OC&dib=eyJ2IjoiMSJ9.P7vXMM_I9PT-Rwo9noppfD_1BirxD7DA2muKNW281ksKQZoJCQw_FpC0ZgbOmFlB4iTrbG9FsGg-zzskkJD_5frVtEXmImby4i2wVwjZ0jomjUzIgo2cjscRqiHi-rBqOE_5RT2wT1bqbPd8BlTWhlW8GacZ_zTbp_6OhFyEvlkc0ClKN49jJJHg1zRml9m4A0-dJWd5m7UiSFh8A1VWWbn6GJ8-K1DMouHuG6Ygdg0.pRhrsQC_2UG4DJvo2AUjdKNDtCY2Sk5xyb1UojXdlw4&dib_tag=se&keywords=tiny+bluetooth+keyboard&qid=1710044375&s=books&sprefix=tiny+bluetooth+keybo%2Cstripbooks%2C729&sr=1-1-catcorr).

I know it's not exactly what you're looking for though. Can you give us a little more info: what device you want to pair this with and your reasoning for wanting to use a bluetooth number pad?

**Comment by sspanak** [comment]
> The biggest issue is the layout. Keyboard number pads are reversed from phone number pads (top row on keyboard number pad is 7 8 9, where as a phone number pad is 1 2 3)

This is not a problem. Traditional T9 is able to handle reversed keyboards. Go to: Settings -> Keypad and enable "Reverse Key Order". This way you can type using any computer keyboard connected to your phone. You will just have to get used to 7, 8, 9 actually produce 1, 2, 3.
