### ISSUE TITLE
Suggestion for README: List of Phones(with physical keyboards) well-supported by tt9 app

### ISSUE THREAD

**Issue by rjolina** [sspanak/tt9#467]
I think it would be a good idea to add a list of phones (perhaps suggestions in this thread?) on which the app works well.

**Comment by amity** [comment]
CAT S22 FLIP is great with it.

**Comment by sspanak** [comment]
> I think it would be a good idea to add a list of phones (perhaps suggestions in this thread?) on which the app works well.

Sorry, this is not really possible. I don't have a bunch of phones to test on and guarantee compatibility. The only phones I have are actually listed in the readme: `Qin F21 Pro+ / Android 11; Energizer H620SEU / Android 10; Vodaphone VFD 500 / Android 6.0`. And the ones that reportedly have many problems are Kyocera and Sonim, also noted in the readme.

It's the best I can do.

**Comment by sspanak** [comment]
I have updated the README.md [compatibility section](https://github.com/sspanak/tt9/tree/docs-30#%EF%B8%8F-compatibility) to reflect more clearly the tested devices. I guess this solves the issue.
