### ISSUE TITLE
Dollar Sign?

### ISSUE THREAD

**Issue by theancientways** [sspanak/tt9#473]
Am I missing something or is there no dollar sign $ in the symbols set? On my phone (Sonim XP3plus), I get a symbols list by pressing 1, or 0, I don't see a $ or any other type of currency for that matter.

**Comment by sspanak** [comment]
Since v28.0 there has been slight reorganization. Now all currency symbols are accessible using 0 + Next Mode key. See [the manual](https://github.com/sspanak/tt9/blob/v29.0/docs/user-manual.md#0-key).
