### ISSUE TITLE
Feature request: Newline capitalization

### ISSUE THREAD

**Issue by WallK** [sspanak/tt9#477]
I would like to have an option to enable a feature that will:
Capitalize the first word after newline

Usecase:
I generally don't end my sentences with a period while texting or writing on the internet
And I often start new sentences on new lines, so it would save me a press to capitalize the first word

ER:
Lorem ipsum↵
Dolor sit amet

AR:
Lorem ipsum↵
dolor sit amet

**Comment by sspanak** [comment]
Sure, but I would like to have it as a separate option. Personally, I would not want capitalization after a new line.

**Comment by WallK** [comment]
Yes, that's what I ask for
Thanks!
