### ISSUE TITLE
Qin F21 Pro the Backlight is not working

### ISSUE THREAD

**Issue by thagata** [sspanak/tt9#492]
When I enter the pin it works once then not again.

**Comment by sspanak** [comment]
I realize the backlight is part of the phone keypad, but software keyboards do not control that, they only generate text and numbers and put them in the foreground application. It's not their job to deal with the backlight.

Anyway, this is a known problem with the Qin F21 Pro. People on the Internet have found different ways of solving it. I would recommend looking up for help on Reddit, some Telegram group or just searching for a fix on Google. I should be easy to find what you are looking for.
