### ISSUE TITLE
Sonim XP3plus issues: status bar not visible, add-word shortcut and language switch shortcuts not available

### ISSUE THREAD

**Issue by wazroth** [sspanak/tt9#495]
This should probably be separate issues, but since they're all on the same device I'll just inventory them here.

In the Sonim XP3plus (XP3900), TT9 works, but there are several issues, which appear in every text field I've encountered so far:

- The status bar with the predictive display, etc., does not show on the XP3plus. (Image attached). I've tried hitting "OK" as suggested in #429 and that doesn't seem to do anything. There's also no display of the current input method when switching with #. (In settings, "On screen layout" is set to "Suggestion list only".)
- Pressing * does not bring up the add-word menu in any circumstance.
- Long-pressing # does not bring up the language change menu, it just changes the input method like a short press.

It's entirely possible this is user error; I see there are other XP9plus users among the folks submitting issues and I don't see these reported yet. I'm happy to take suggestions or dig into the device settings on request if more information is needed.

This is a 3900 (P14301) from AT&T, unlocked. 

![image](https://github.com/sspanak/tt9/assets/11889113/3596ea7d-2a1a-48e0-bbb2-f8cb36a641e8)

**Comment by sspanak** [comment]
You are experiencing #393 and maybe #490. Please, try the last APK posted in #393 and follow it for updates.

> Long-pressing # does not bring up the language change menu, it just changes the input method like a short press.

There is no language menu. If you have enabled multiple languages, it just switches to the next one. This is probably confusing, when you can not see the UI. 

I didn't know XP3900 and XP3800 behave so differently and rushed a bit with releasing v30.0. But now, I believe we have almost ironed the problems out.

**Comment by wazroth** [comment]
Thanks! 

For the language key, I guess I don't know what to expect since I don't see the interface (as you rightly understood!), but as far as I could tell, long pressing didn't change the language either (I have English and Spanish configured).

I'll try 30.14 and report back.

**Comment by wazroth** [comment]
30.14 is a bit better -- I can get the interface to show! -- but the interaction to get it to show is unexpected. Hitting "OK" on the empty text field does nothing. Hitting OK after a typeahead has started gets the interface to display, and then through the end of the typing excursion it seems to work well, with the # and * buttons working precisely as described in the documentation.

It's a bit weird that i can hit "OK" to choose a typeahead suggestion and then hit "OK" again immediately to send the message, but if I recall there's a specific reason you can't or don't want to disable this functionality. (For what it's worth, the XP3900 has a "send" function coded to one of the dynamic keys in the messenger app but I'm not sure that there's the equivalent throughout the OS. If there were a way to disable the functionality just within the messenger app it could spare a user some premature message-sends. The default T9 implementation has this issue too, though!)

The behavior in other text fields is less predictable.  When composing a new message, in the "To" field, there doesn't seem to be a way to get the interface to show. Clicking "OK" before typing just moves to the message field. Clicking "OK" after you've started typing sets what you've typed so far as the intended contact (putting the typed text in an oval, etc.) even if the typed text doesn't match an existing contact or isn't a valid phone number or email. Then, pressing "Back" after that's happened causes the typeahead text to reappear in the contacts field (as though you'd started typing a new contact name) and must be cleared out before you can hit "back" to clear out the prematurely-created contact. When the typeahead does match a contact, you also need to hit "back" twice to backspace; the first "back" clears the display of the matched contacts, and the second "back" actually backspaces. This is probably a consequence of how the "back" button is assigned to both Clear and Backspace and I'm not sure there's much to be done about it, but thought it was worth sharing.
 
In the Contacts app, there also doesn't seem to be a way to get the UI to show. Hitting "OK" does nothing if no contacts match or selects the first contact that matches the current typeahead text. But the backspace behavior is better than  in the "to" field of the messenger composer.

I haven't tested  the web browser yet. The issues with the contacts and the "to" field of the messenger composer are less critical than the messenger text field, to be sure.

I can take a screencap of any of these interaction patterns if desired; let me know.

**Comment by sspanak** [comment]
All I ask is to keep all communication about the OK key problem in one place. Let's continue the discussion in #393.

Btw, I've just posted a new beta APK in #393. Please try it out. I think I got it right this time.

As for your wish OK not to send messages at all, this is not a problem with TT9. The messaging app is designed to work this way. This is confirmed by the fact that the native keyboard does the same. I do not want to override the standard operation, because of many reasons, but I can add a compatibility setting, especially for the XP3900, just like there is "send with OK in Facebook Messenger" or "send with OK in Google Chat". If you like the idea, please create a new issue. I can do it at a later time.

**Comment by neutralinsomniac** [comment]
I just tested your latest build from the xp3900-hacks-for-real branch and HOLY SMOKES IT WORKS!!!! No need to hit OK to get the suggestions to show, it just works in signal + the stock apps. Thank you so much!!!!
