### ISSUE TITLE
No way to input '@'?

### ISSUE THREAD

**Issue by neutralinsomniac** [sspanak/tt9#497]
I can't find '@' in the punctuation list (by cycling through them with the '1' key). Am I missing something?

**Comment by sspanak** [comment]
You can type math and special characters using the 0-key. 1-key is used for punctuation and characters normally used when typing text.

See the [v30.0 manual](https://github.com/sspanak/tt9/blob/v30.0/docs/user-manual.md#0-key) if you have more questions.

**Comment by neutralinsomniac** [comment]
ope. thank you!
