### ISSUE TITLE
Greek question mark `;`

### ISSUE THREAD

**Issue by GiorgosXou** [sspanak/tt9#510]
The Greek question mark is `; ` not `?`. Although informally (on Internet) `?` is commonly used too. Additionally, more emojis would be great. 

Btw thank you for this keyboard (:

**Comment by sspanak** [comment]
According to [this website](https://daedalus.umkc.edu/FirstGreekBook/JWW_FGB2.html) the Greek question mark is the same character as the Latin semicolon. I can also see a character called "middle dot" or "dot above the line" is used in Greek, but TT9 does not support it.

Given that `;` is already in the list, it means I only need to replace the Latin `?` with Greek `;` and the Latin `;` with Greek `·`, right? 

> Additionally, more emojis would be great.

This is not really on the priority list. However, you can add your own emojis just like you can add new words. Find the one you need on the Internet or send it to yourself from a computer, then hit the Add Word button. See more info in [the manual for v31.0](https://github.com/sspanak/tt9/blob/v31.0/docs/user-manual.md#add-word-key-default-press-).

> Btw thank you for this keyboard (:

Enjoy and invite all your friends to the party!

**Comment by GiorgosXou** [comment]
> Given that ; is already in the list, it means I only need to replace the Latin ? with Greek ; and the Latin ; with Greek ·, right?

Exactly! 

> ... However, you can add your own emojis just like you can add new words. 

Thanks!  Exactly what I needed. A nice feature would also be if via specific words it autocompleted emojis.

> Enjoy and invite all your friends to the party!

🥳
