### ISSUE TITLE
[Feature Request] Use keyboard as touchpad to move cursor

### ISSUE THREAD

**Issue by pawlosck** [sspanak/tt9#512]
In Samsung keyboard, there is one great feature.
When I touch and hold space bar, whole keyboard is grayed out and I use whole keyboard to control position of cursor. Keyboard is switching to touch pad mode. It's very fast and precision mode to edit text or fast move to different location.
When I move finger slowly, then cursor is very precision and when I move fast, I can move cursor very fast.

Is there chance to implement it?

**Comment by sspanak** [comment]
Are you talking about moving the text cursor on a touchscreen phone? If so, I am planning to do it in #240. The left and right keys in the suggestion bar will have that extra function when no suggestions are displayed.

**Comment by pawlosck** [comment]
I read it but my idea is much better. Do you have any friend with Samsung phone ? If yes, try samsung keyboard and you will see, why my idea is better. If not, I will try to record movie to show it, but first I have to find any camera to record it.

In my suggestion, you don't need any buttons, because all buttons are hidden. You just touch and hold space button (you can use other button) to hide all buttons. After that, you can swipe finger using whole screen and move cursor left, right, down, up. It's very helpfull when you have opened long note/SMS (for example 30 lines or more). You don't have to touch many times button to move cursors or change direction. You just swipe finger and cursor is moving.

**Comment by sspanak** [comment]
You can do the same by touching the text. There is no need for keyboards to provide a second cursor control area. Or am I missing something?

Either way, what you suggest is very much oriented towards touchscreen phones. But Traditional T9 is mostly focused on devices with hardware keyboards or keypads, as well as providing very similar experience on touchscreen devices. And... there is no swiping on the hardware keys. The idea is not really applicable here. Sorry, I'll have to reject it.

**Comment by pawlosck** [comment]
Yes, I can touch the text, but I have big fingers and I can't set correct position too precise. If you want, I can record a movie and show you.

**Comment by sspanak** [comment]
I get the idea. My point is I am not willing to invest time in touchscreen-only features.
