### ISSUE TITLE
Looking for volunteers to test the Google Play early release

### ISSUE THREAD

**Issue by sspanak** [sspanak/tt9#526]
Traditional T9 is now on its way to the Google Play Store. But before publishing it, Google requires at least 20 people to install the early release version and keep it for at least two weeks.

If you would like to see TT9 on the Play Store, you can help by joining the testing group. All you are required to do is:
1. Join the testing group [here](https://groups.google.com/g/tt9-testing).
1. Become a tester and install the Play Store version [from here](https://play.google.com/apps/testing/io.github.sspanak.tt9). If you already have TT9, you will have to uninstall it. Unfortunately, the Play Store uses `.aab` format instead of `.apk`, making upgrades from the Github or the F-droid versions impossible.
1. Keep the Play Store version for at least two weeks.

That's it! You don't really have to test it as a professional. You can just continue enjoying TT9. You will automatically get the next version when it becomes available and will no longer need to download APKs manually or deal with third-party app stores.

_**UPDATE:** It is not longer necessary to share your email. Just join the Google group from the link above._

**Comment by maverick74** [comment]
I suppose we should send that e-mail from the same e-mail we have associated to the play store, no?

**Comment by sspanak** [comment]
> I suppose we should send that e-mail from the same e-mail we have associated to the play store, no?

Correct!

**Comment by sspanak** [comment]
Resolved thanks to Testers Community.

**Comment by maverick74** [comment]
Wow... i was not able to subscribe over the weekend and was planing on doing it yesterday on the desktop, but didn't find the time to.

Now that i was about to... well it's no longer necessary!!!

( i'm happy, however, to see users stepping up so fast!!! great people :) )

**Comment by sspanak** [comment]
Indeed!
