### ISSUE TITLE
First letter overwritten by the next one on the start of typing 

### ISSUE THREAD

**Issue by WallK** [sspanak/tt9#533]
If you start typing on the untapped (?) field -- first letter will appear, but when you type the next one -- it will disappear and only second character will remain

STR:
1. Open app with focused input field
2. Do not tap on it (?)
3. Press any character dpad key to input letter
4. Input another letter
5. Observe

ER: Both letters stay in the field
AR: First letter disappears

Video:

https://github.com/sspanak/tt9/assets/4513545/a1aad0ca-fe58-4442-bb0c-116ab461241d

**Comment by sspanak** [comment]
This problem seems to come back every once and a while. I believe I have just fixed it in the newest [v33.0](https://github.com/sspanak/tt9/releases/tag/v33.0). 

Also, it should appear on Uptodown within 2-3 days. And F-droid is slowest, as usual. Just saying, in case you prefer any of them.

**Comment by WallK** [comment]
Hmm, I did not search for closed issues, sorry
Thanks, I'll test the new release!

**Comment by WallK** [comment]
Works fine now, thank you!
