### ISSUE TITLE
Specific website input password field gets all keypresses as input

### ISSUE THREAD

**Issue by zkrx** [sspanak/tt9#536]
This is a phone operator login page. Try entering a password in abc mode. All keypresses are input as character. I don't know what they're doing to cause this behavior: 
https://www.sunrise.ch/mysunrise/en/residential/login

**Comment by sspanak** [comment]
> All keypresses are input as character.

I don't quite get what do you mean by this. Could you please clarify or if possible, record a video showing the problem?

For me, it works fine both in Firefox and Chrome, latest versions. Are you using some sort of a custom browser? If so, it may be causing the problem.
