### ISSUE TITLE
No Haptic feedback?

### ISSUE THREAD

**Issue by Ejurety** [sspanak/tt9#541]
I was so excited to find a working T9 keyboard, I installed it, and loved how easy it was to use. But my dreams were annihilated as I immediately realised there was no haptic feedback (rumble) on key press. will this be added? I can't use the keyboard without haptic feedback, so I have uninstalled until it is added, or I find a replacement

**Comment by sspanak** [comment]
The virtual keypad is still a bit incomplete, but I didn't realize how important this was.

I am going to do it in #240. Stay tuned and follow #240 for updates.

**Comment by Ejurety** [comment]
Thanks!
