### ISSUE TITLE
Suggestion: Command Palette enhancements

### ISSUE THREAD

**Issue by WallK** [sspanak/tt9#542]
Hello!
I've used command palette and voice input now, and have some ideas that could be beneficial to user experience

1. Close command palette by Backspace:
Usually, canceling whatever I've done just now is done by Backspace in the tt9 keyboard. Like opening symbol suggestions, pressed one too many letters and so on. But pressing Star and getting the Command Palette requires me to press Back (which is on the opposite side of the keypad). Basically, by the power of habit I'm pressing Backspace couple of times before realizing I need to press Back button.

2. Allow pressing OK to send while Command Palette is open
This is mostly about voice input. The flow right now is: Press Star + 3, say something, press Back, press OK to send. And to dictate next message -- I need to open Command Palette again. My suggestion is to allow sending whatever you've just dictated without closing Command Palette

Thank you!

**Comment by sspanak** [comment]
I wasn't really sure what is the best way of handling the hotkeys when the command palette is open. 

Thanks for the suggestions! I'll implement them in the next version.
