### ISSUE TITLE
Dictionary Word Corrections

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#548]
Dictionary: Portuguese / PT

Words in **wrong** form - VS - words in **correct** form

DOS - dos
São - são
TB - tb
PT - pt
Mota - mota
Pera - pera
Damas - damas
Passo - passo
TV - tv
ABC - abc

**Additional info**: most of these only appear capitalized in the middle of a sentence. If we write them as a first word the system automatically inverts the first letter to non-capital!

Words to be added not specific to the Portuguese dictionary:

KDE

**Comment by sspanak** [comment]
I'll check them out.

"TV" probably came from the Google dictionary and it stands for "television". Does it have a different meaning in Portuguese? They tend to (incorrectly) put some English words in the other dictionaries, so I wouldn't be surprised if it is wrong.

**Comment by maverick74** [comment]
> "TV" stands for "television". Does it have a different meaning in Portuguese?

No, it has the same meaning! But we don't necessarily use it in caps!

You may keep it that way if you prefer, however! It's not "wrong"!

I, personally don't type it in caps and I also use it as an abbreviation for "talvez"...

**Comment by sspanak** [comment]
I don't use Portuguese, so I have no preference in this case. :slightly_smiling_face: Let's make it feel more native and convert "TV" to "tv".

**Comment by maverick74** [comment]
hope it's not too late to add:

Vale - vale
daL - dal

XP

(no problem if it's too late for this release)

**Comment by sspanak** [comment]
That's fine, I still have a couple of small tasks to do for the next version. It is not too late.
