### ISSUE TITLE
Restore the Add Word functionality

### ISSUE THREAD

**Issue by sspanak** [sspanak/tt9#55]
After completing #18, #14 and #26, adding new words functionality no longer works.

- ~~Take away the legacy function in T9DB and create a new one in `DictionaryDb`.~~
- ~~New words are added with priority of 1.~~
- ~~Remove the old database package~~
- ~~Re-wire all functions and the UI.~~
- ~~Update the inputConnection with the newly added word.~~
- ~~If possible, remove `LangHelper.java`.~~

**Comment by maverick74** [comment]
This seems to no longer be working again (at least in my case).
I choose to add word and after i press OK it simply does not add the word

I'm on android 8.1

@sspanak can you reproduce or do you need anything else from me?

**Comment by sspanak** [comment]
This is issue is about adding the functionality, because I had to remove it temporarily.

Anyway, there is no OK button on the "Add Word" window currently. Please, open a new issue with a screenshot or a video, for me to understand better what exactly is going on.
