### ISSUE TITLE
Which flavor should F-Droid publish?

### ISSUE THREAD

**Issue by linsui** [sspanak/tt9#550]

**Comment by sspanak** [comment]
Let's use the lite version. I've made sure the APK name remains the same for the server to pick it up without any adjustments.

Or has there been a problem? I haven't checked the latest build logs.

Also, from user perspective, upgrading to either version should be completely transparent, now and in the future.

All in all, I tried to make the transition as easy as possible for everyone.

**Comment by linsui** [comment]
Thanks!
