### ISSUE TITLE
Longer words suggested before all possible combos

### ISSUE THREAD

**Issue by dbueche17** [sspanak/tt9#556]
New to this but I'm having trouble with longer words being suggested before all possible combinations of the inputted characters. Let me know if this makes sense!

**Comment by sspanak** [comment]
Could you please provide an example? Does it happen every time?

**Comment by dbueche17** [comment]
I think it's more of a function thang than a bug. I type somewhat colorfully and say i want to text my friend and call her rachy, over rachel, I'm given pachy and pachyderm and pachysandra and pachydermal, and it completely ignores the other combinations of 72249. I would prefer to see those combinations, eg. scagy or rachy, which may not be words, before jumping to possible 9 letter dictionary words. If this is asking too much no prob but i think it could be beneficial. I've tried adding some words to the dictionary and haven't had any luck with that.

**Comment by maverick74** [comment]
i think i got it: it's really a case of adding the "_rachy_" word to the dictionary.
If it's not a word and it doesn't exist on the dictionary it won't be suggested.

As soon as it's added it does show up! (tested here!)

after typing the word "manually" place the cursor right after the last letter or "inside" the word, press + and add it.

the next time you type it it will be shown!

**Comment by sspanak** [comment]
Exactly! Thanks, **maverick74**.

Just one more thing to add. There are 432 possible words for `72249` but most of them are nonsensical. If TT9, or any T9 keyboard for that matter, displayed all possible combinations, finding the word you need would become impossible in practice. That's why the suggestions are limited only to the dictionary words.

**Comment by dbueche17** [comment]
hey thanks for they replies that makes a lot of sense. I've been able to add a lot of words to the dictionary using that advice—previously i was holding down on the word and selecting add to dict when it appeared and that wasn't working. Now i've got it sorted, thanks!

**Comment by maverick74** [comment]
> previously i was holding down on the word and selecting add to dict when it appeared and that wasn't working.

Oh... I hit that brick wall as well ahahah! You were actually adding the words to the Android dictionary instead of tt9's!
That's why it didn't work!

Glad it's working now 🙂

I believe this can be closed, then...
