### ISSUE TITLE
Adding Apostrophe to Options for Double 0 Key Press

### ISSUE THREAD

**Issue by alexdc-info** [sspanak/tt9#561]
Based on the order in which characters appear after pressing "1" (and the looping behavior that allows easy access to "?" and "!"), I would prefer to have the option of selecting an apostrophe "'" as the result of a double 0 key press.

**Comment by alexdc-info** [comment]
I realize that this may just come down to my personal preference, in which case please ignore it. 

I figured I would take a shot at it as I haven't made a github contribution before. I've meant to assign this issue to myself - if I haven't yet, it's because I'm struggling to figure out how.

**Comment by maverick74** [comment]
As you may not be aware, i'll share a shortcut i think it's even better (because using your idea you actually have to press twice on 0)

if using the english laguage (as an example) and you intent to write " **_I'm_** " you just need to press keys 

4+1+6

and TT9 will automatically "guess" that the punctuation sign you were searching for when you pressed 1 was actually the " ' "

please check if it solves your use case and if it does, i guess you can close this

**Comment by sspanak** [comment]
@alexdc-info, I can easily add the apostrophe to the 0-key list, but it doesn't sound right. What is the exact problem you are trying to solve? 

As **maverick74** pointed out, you don't need to search for it to type contractions. Just press 1-key and TT9 will guess what you want to do. Even more complex words are possible, for example "rock'n'roll". Besides apostrophes, it will guess dots in domains, e.g. `google.com` = `4664531866`.

What else is missing? Or do you need to type non-standard words or perhaps sequences of special characters? In that case, T9 keyboards indeed require more time and patience.

@maverick74, there is [a short section](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#1-key) about the 1-key, but typing contractions is not explicitly mentioned. Having used a Nokia back in the days, it feels so intuitive that I didn't think it needed to be clarified.

**Comment by maverick74** [comment]
> @maverick74, there is [a short section](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#1-key) about the 1-key, 

Yeah, i noticed it! that was the first place i looked!

> but typing contractions is not explicitly mentioned. Having used a Nokia back in the days, it feels so intuitive that I didn't think it needed to be clarified.

ahahah right!!! but... lets not forget that was 20+ years ago 
( No!!! **We're not old**!!! We're **wiser** and " **_getting better everyday like Porto wine_** "- as we say around here XD )

**Comment by alexdc-info** [comment]
Thank you @maverick74 and @sspanak! 

As you guessed, I was not aware that this was possible, and I agree that this is much better! It's my first time using T9, and I didn't pick up on it when I read the manual. It's entirely possible that this is just me though and that I would have stumbled upon it given enough time.

Thank you for your wisdom :)

Have a nice day!
