### ISSUE TITLE
Feature request: Hotkey for Speech-to-text

### ISSUE THREAD

**Issue by horomancer** [sspanak/tt9#569]
Currently, I can press '*' and '3' to enter Speech-to-text. i've found this really useful and would love to be able to program it to a hotkey. My phone has a PTT key which would be an awesome thing to program to, as it would allow for very quick note taking, but just being able to hold the '#' or 'Call' key to enter this mode would be great

**Comment by sspanak** [comment]
One of the reasons for introducing the command palette was to reduce the complexity of handling many hotkeys. I may think about it, but as of now, I don't feel like going back to that. I can't promise I'll do it. Sorry!

**Comment by sspanak** [comment]
Closing this in favor of #581.

PTT buttons are specific to each device. Unfortunately, I can't provide support for that button, unless I have the phone to test with.
