### ISSUE TITLE
Speech-to-text not accessible when Appearance is set to Invisible

### ISSUE THREAD

**Issue by horomancer** [sspanak/tt9#570]
When Appearance is set to 'Invisible', command keys can not be accessed and the key combo '*' , '3' can not be used to enter Speech to text mode.
A small problem, and 'Suggestion list only' is the superior display method (especially if word prediction gets upgraded in the future)

**Comment by sspanak** [comment]
This is already fixed. Please check out the newest [version 35.0](https://github.com/sspanak/tt9/releases/tag/v35.0). In the next couple of days, it will become available on Play Store, F-droid and Uptodown, too.
