### ISSUE TITLE
Difficulty adding a word that is not in the dictionary

### ISSUE THREAD

**Issue by abea210** [sspanak/tt9#571]
Hi
When I'm in word prediction mode,
And I write a word that is not in the dictionary's databases,
So you can't add by going with the arrow to the end and writing add a word,

But you have to delete the letter, change the keyboard to ABC and write down the letter, and then add it to the dictionary using the star key.
Which I think if it can be arranged it will be in the last option of the word proposal

Thank you

**Comment by sspanak** [comment]
TT9 is meant to provide Nokia-like experience but when it comes to adding words it is a bit different. There is no "add" entry at the end of the suggestion list. Instead you can add words by simply invoking the "add" function. Press * + 2-key, when using a hardware keypad, or press the "+" button when using the on-screen keypad.

The only requirement to add a word is to have the text cursor in the word or right next to it. It doesn't matter if you are currently typing a word or if you have already typed it and went back to it. And certainly, you don't have to go to the end the word, erase letters, change the typing mode or whatnot. None of this is necessary.

I hope this helps!

**Comment by abea210** [comment]
Hi
Thank you
Maybe it doesn't work on my phone? So I will write what I have,
If the keyboard is in prediction mode T9, and I want to write a word that does not appear in the dictionary, it is not possible to add it by a star and 2, but first of all you have to cancel "Prediction" and then write in normal letters, then add it to the dictionary by a star.
But if I'm in Halizoui and I click on the star and 2 to add a word, then it doesn't allow it, because it shows you that you need to type the word first and then stand next to it and add.
Isn't it like that, but only for me, but everyone can add a star?

**Comment by sspanak** [comment]
I am unsure what exactly is going on. Could you please send a screenshot, or even better, a video showing the problem? Also, what language are you using?

**Comment by abea210** [comment]
https://github.com/user-attachments/assets/53223da9-9b7b-4498-8bb6-889738a44fa2

**Comment by abea210** [comment]
https://drive.google.com/file/d/1l8tNBWcpWc_AeF_OrLlN0-Kqkshm0Gsk/view?usp=drive_link

**Comment by abea210** [comment]
I attached the video, I tried just for example to write "Hmw"
You can clearly see the long and difficult process because in this version there is no option to add a word. You just have to first change the keyboard to ABC, etc. and only if you do that you can add the word. as you see in the video. Is it because it's an older android?

Thank you

**Comment by sspanak** [comment]
As far as I can see, everything is working properly. The solution to your problem is in the video, in the toast message that appeared twice. You must move the cursor inside or next to the word you want to add. If it is somewhere else, there is no telling which word you are trying to add, so nothing happens. Keep trying and you will make it eventually.

As for typing new words in Predictive mode, there is a section about [the filtering keys](https://github.com/sspanak/tt9/blob/master/docs/user-manual.md#filter-suggestions-key-default-d-pad-up) you may find useful. Check it out!

**Comment by abea210** [comment]
I understood, thank you
Could you add in the word suggestions that the last suggestion would be "adding a word"

**Comment by abea210** [comment]
Hi
I found in your older versions that it did work it was possible to add a word easily
I will attach a video
Thanks

https://github.com/user-attachments/assets/25fbdd09-300b-4cef-af12-d63f49cde608

https://drive.google.com/file/d/1hm_OCpeGXHiJT3g6KWwLYTdDKqmnUtmz/view?usp=drive_link
