### ISSUE TITLE
Pressing "End" button while MPV is playing stops MPV playback.

### ISSUE THREAD

**Issue by spiralingtides** [sspanak/tt9#574]
I'm not sure if this is TT9 or MPV. Pressing End while MPV is playing stops playback before going to the home screen. Switching apps and then pressing end does not end playback. Pressing End while phonograph is playing does not end playback on phonograph though, so I'm checking here first.

**Comment by sspanak** [comment]
I am sorry, I have no idea what you are saying. What is this "End" button you are referring to? 

Android does support the "End" key of computer keyboards, but I really doubt you have connected one to your phone/tablet/whatever. Besides TT9 does not handle it in a special way, it just passes it through and lets the current application decide what to do.

Or do the mentioned applications have their own "End" key, in the UI (I haven't used them, so I have no idea)? If so, the key response is entirely up to the application. Pressing it does not even make it to TT9.

**Comment by spiralingtides** [comment]
My bad. Its the "End Call" key, which on my device doubles as a "Home" button and is also the Power Button.

**Comment by sspanak** [comment]
Oh, I see. TT9 ignores that key. It is up to the players what to do when it is pressed.

**Comment by spiralingtides** [comment]
Thank you, with that information I'll open the issue up on the MPV github page.
