### ISSUE TITLE
Feature Request: Fast add word key

### ISSUE THREAD

**Issue by lilor159357** [sspanak/tt9#575]
Thank you for your awesome keyboard! it's really helpful! 
an a suggestion: an option for auto adding an word to dictionary without dialog.
for now i am using keymapper app to automate the process of pressing the "2" and the the word adding etc.
 it could be very helpful if there was an option to add an word immediately on key press, for faster typing experience.
thank you!

**Comment by sspanak** [comment]
The dialog is there to ensure people are clear what they are adding. For example, if you have the word `rock'n'roll` and the cursor is in the middle of `rock`, TT9 will pick up only `rock`. Or, if you have typed " hello🙂" and the cursor is between "hello" and the smiley face, it will attempt to add the smiley face.

I think it is important to avoid confusion in such cases, so I'd rather keep the dialog. I guess, over time, you would learn how TT9 works and the dialog would become somewhat useless. In such case, I am OK with adding a setting to skip it, but not remove it completely.

As for the "fast key", I am strongly against it. In fact, there used to be a separate key, before introducing the command palette, but there were two problems with that:
1. Adding more and more shortcut keys and became too complex to maintain (as stated in #569).
2. Some phones have very few available keys, making it impossible to assign all TT9 functions. Currently, they are 7. But how to fit 7 functions on, for example, only hash and pound keys?

For these reasons, I had to find a more flexible and simpler solution, making some compromise with the ease of access.

I agree to fulfill only the first part of the request, hiding the dialog.

**Comment by lilor159357** [comment]
thank you!
About the fast key: as I said, I am using an app that performs for me the automation of the adding word process; therefore, in fact, I am not using the new command palette, so maybe having the option to choose which functions the keys perform, with the option to give up on a function, will solve the question of how to fit all the functions in the few keys.
and sorry for the poor English.

**Comment by sspanak** [comment]
Even now it is possible to reconfigure the shortcut key for each function. It can be done from Settings -> Keypad -> Hotkeys. The problem is there too many functions but too few keys.

Anyway, I am not adding back the Add Word key. Adding words should not be something you do too often and as such, invoking it using two key presses instead of one, shouldn't be a huge problem.
