### ISSUE TITLE
Feature request: Command Palette options as hotkeys

### ISSUE THREAD

**Issue by DarthFlip** [sspanak/tt9#581]
Edit: I see this was already requested in #569 #575 (But I still would love to have this option:)

**Comment by sspanak** [comment]
Man, this really backfired! I created the command palette to reduce the number of hotkeys and now everyone wants more hotkeys. :smile: Fine, I'll do it in the next version.

I would appreciate some help with translating the following:

- "Call", as the name of the call key, in: German, Italian, French, Dutch, Turkish
- "hold" the clarifying comment next to keys that can be held. Looking for German, Italian, French, Dutch, Turkish translations
- "Restore Default Keys" in German, Italian, Dutch
- "Default key settings restored." in German, Italian, Dutch

Commands:
- "Clear Filter" in: German, Portuguese, Italian, Hebrew, Dutch
- "Filter Suggestions" in: German, Portuguese, Italian, Hebrew, Dutch
- "Previous Suggestion" in: German, Portuguese, Italian, Hebrew, Dutch
- "Next Suggestion" in: German, Portuguese, Italian, Hebrew, Dutch
- "Next Language" in: German, Italian, Dutch
- "Input Mode" (the key for toggling between 123, ABC and Predictive) in: German, Italian, Dutch

And... I'll be looking forward for a beer or two.

**Comment by sspanak** [comment]
Well, the task is completed, so I am moving the translation stuff to #588
