### ISSUE TITLE
Turning off auto-capitalisation results in all words being capitalised in predictive mode

### ISSUE THREAD

**Issue by Void345** [sspanak/tt9#596]
I would like to be able to type in all lowercase 
I had a poke around the settings and couldn't seem to be able to make it do that
Sorry if I missed it!

**Comment by sspanak** [comment]
1. Go to Settings -> Keypad
2. Scroll down to the Predictive Mode section
3. Turn off the Automatic Capitalization setting
4. Go to some application where you can type and type some name which has a capital letter, e.g. "John"
5. Press the Typing Mode key (default: `#`) until the word changes to lowercase.

TT9 should remain in lowercase mode until you change it again or until some app overrides it.

**Comment by Void345** [comment]
Ohhh I hadn't tried that. It's working now, thank you! :)
