### ISSUE TITLE
Add a hotkey for quick-switching to the next keyboard

### ISSUE THREAD

**Issue by sspanak** [sspanak/tt9#599]
Based on the discussion in #553, an idea popped up to add a new hotkey for switching directly to the next active keyboard, to speed up switching. Currently, the Change Keyboard key displays a list of all keyboards from which the user can select the desired one, even if there are only two. But the later takes several clicks + time to read and find the next keyboard.

Requirements:
1. Add a Next Keyboard function. On API >= 28 we can use `InputMethodService.switchToNextInputMethod(false)`, and on older devices: `InputMethodService.switchInputMethod("NEXT_KEYBOARD_ID")`, assuming we have obtained the next keyboard ID from `InputMethodManager.getEnabledInputMethodList()`
2. ~~Add a Next Keyboard hotkey + translations, for devices with physical keys~~ - this is not necessary, because the problem concerns touchscreen devices.
3. On the virtual keyboard, sliding the Input Mode key to either direction, selects the next keyboard.

**Comment by sspanak** [comment]
@maverick74, I am not entirely sure about your idea. Does sliding the "keyboard" key to both directions make sense?

**Comment by maverick74** [comment]
> @maverick74, I am not entirely sure about your idea. 

That was just an idea! In fact _unexpected_ uses _right-up slide_, which I think it's kind of difficult to get! That's why I mentioned sliding right

Does sliding the "keyboard" key to both directions make sense?

If you mean sliding to either right or left it makes sense! If you mean having to slide right and then left, not that much!

**Comment by sspanak** [comment]
> If you mean sliding to either right or left it makes sense!

Exactly.

Alright, let's do it as described.
