### ISSUE TITLE
italian language dictionary a bit lacking

### ISSUE THREAD

**Issue by leonardo-lena** [sspanak/tt9#601]
Hi, I've recently installed TT9 because I'm tired of spelling mistakes using QWERTY on my phone... I love the app and its general functions, especially the ability to immediately switch up languages, but I found the Italian dictionary a bit lacking: some times I have to add extremely basic words, like "fare" which just means "to do" or "dare" which is "to give". There are other conjugations of the verbs but not the most basic. Another example is the lack of the word "poco" which means "a little", but the suggestion of "pocolino" which is not even a word.
This is to suggest that probably it could be beneficial finding a different dictionary. I personally have found a github with a .txt that's a bunch heavier than what is currently in use (about 58MB) and therefore I think could contain a lot more of the language. T9 works if the language dictionary is complete, else it's more of an issue than a help, so it would be great if you almost never had to add words unless they were for example personal surnames and such.

**Comment by sspanak** [comment]
Hi and thanks for reporting.

It seems that I have accidentally deleted almost all 4-letter words during the last update. Currently, there are only 38. I will restore them in the next release.

As for the 58Mb word list, I am not so sure about using it as it is. Currently, Italian is 7.5 Mb and 652273 words. Roughly estimating, the huge one will contain about 5 million words. I have not tested and can not guarantee TT9 will work properly with so much data. Even at 1 million, I notice lag sometimes, so 5 million is probably a bit too much.

Let's restore the deleted words and see how it goes first. If you feel Italian is still off, please open a new issue and we can try adding more words.

**Comment by leonardo-lena** [comment]
ah yes now that I think about it most issues indeed were with 4 letter words. That should definitely fix most of the issues!
