### ISSUE TITLE
Question mark (;) in Greek

### ISSUE THREAD

**Issue by AgentGolder** [sspanak/tt9#606]
Since a recent version, there are 2 unknown other symbols and not the question mark );) available. Please add it back to the [1] key.
Thanks.

**Comment by sspanak** [comment]
I have swapped several special characters between the 0-key and the 1-key in the May release, but the Greek question mark is still where it has always been, at the end of the list. Also, I am not sure what are these unknown symbols. Are you sure the fonts on your phone are not corrupted? Could you please take a screenshot after pressing the 1-key and post it here?

**Comment by AgentGolder** [comment]
How to take a screenshot and how many times is needed to press the [1] key?

**Comment by sspanak** [comment]
I don't know, it depends on the device. On many phones you can make screenshots by holding the volume down and the power key, but it may be entirely different on yours. You need to check your phone manual or just google it.

As for pressing the 1-key, just press it once. If you press it more than once in Predictive mode, you will get the emoji list. But I am not sure why you are asking this question. Nothing has changed in this regard in the past 2 years. I have the feeling you are trying to type using multi-click in Predictive mode or there is something wrong with your phone, but I can't tell at this point.

**Comment by AgentGolder** [comment]
OK. Can you please attach an .apk here with the fix when you make it?

**Comment by sspanak** [comment]
Here is an updated version that fixes the problem I've noticed. Download [v38.24](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v38.24.apk).

**A word of warning.** This version also contains half the changes for the upcoming v39.0. They are not documented anywhere yet. What will most concern you is, there is now a separate SHIFT key for toggling between uppercase and lowercase. The default keys are as follows:
- Press "#": Cycle between 123 -> abc -> Predictive (but not ABC in capital letters)
- Hold "#": Change the language (same as before)
- Press "*": Show the command palette (same as before)
- Hold "*": works like a SHIFT key on a computer. Toggles between uppercase and lowercase.

Also, this version will reset all hotkeys to the defaults. Have it in mind if you have customized any.

**Comment by sspanak** [comment]
@AgentGolder, did it work? Are you still getting unknown characters when you press 1?
