### ISSUE TITLE
Prevent send with D-pad center button whatsapp

### ISSUE THREAD

**Issue by Small-Systems** [sspanak/tt9#610]
For some context I have a Qin F21 pro, touch screen and keypad.
Is there a way you can add an option to prevent sending messages by hitting the center d-pad button?
This mostly concerns whatsapp, I often send messages by mistake whilst typing when I want to select punctuation, so I hit the d-pad center button, but somehow I hit it twice, or the app has already selected the character so I send up sending the unfinished message. I would prefer to send my messages with the touchscreen send button in the whatsapp UI.

Thanks for the great work, I really appreciate this app.

**Comment by sspanak** [comment]
There is a Whatsapp settings for it. See [how to configure ENTER](https://faq.whatsapp.com/1159217535009237/?cms_platform=android).
