### ISSUE TITLE
Keyboard mode key - nitpicking issues

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#622]
Ok... i don't exactly know what to call this issue, but here's a case i believe explains my point:

1- in the middle of a message (using t9 mode in any language) i have to type an extensive number.
2- i switch to the numbers keypad and type the number,
3- now to get back to t9 assisted mode i actually have to type **3 times** on the keyboard key...
(i won't count the times i mistakenly type 4 times and have to get all 3 taps again...)

So, actually, what i mean is that _i think_ there's too much options on the same key.

now, I have **no idea** where to put the various functions, but it's sometimes annoying... so i'm throwing you the _hot potato_ (ahah) 

Regarding the same key - but talking about the CAPS function - there is also another small (personal) detail i use to think about:

Those used to a PC keyboard (i believe gboard functions the same way), use caps in the inverted order! 

Let me explain: 

**on a pc** if you intend to type in CAPS you 

- Press shift, _and then_ the intended letter OR you press CAPS _and then_ the intended letters

on tt9 however you:
- first type the word _and then_ press the keyboard key until you get the desired CAPS mode (either all caps or just the first letter)

so... _mentally_ it's inverted.

yeah... these are all nitpicking issues and you can safely close this (**i'm really ok with it!!!**). There are all these other more important issues to look at... I was just sharing some thoughts about my experience :)

**Comment by sspanak** [comment]
This can be solved by having two separate buttons, one for changing the text case, call it SHIFT or CAPS (I like SHIFT better); one for changing the input mode: ABC -> 123 -> Predictive. There are a couple of things to consider though.

In Predictive mode, when the Automatic Captial Letters setting is on, you don't have much control over the text case. TT9 adjusts it before every word to ensure capitalized proper names, capitalized words at the beginning of sentences and whatnot. It will only preserve uppercase, if you have selected in advance. This means, when the mentioned setting is on, the potential SHIFT key will be useful only after typing a word. And this is the whole idea of Predictive mode - you just type without thinking too much and only occasionally adjust incorrect words. This does not mean I am against having a separate SHIFT key. I agree it makes sense to have it, I just want to point out it may not work as you expect.

My second concern is for when you use TT9 in invisible mode. There will be no indication you have changed anything. Perhaps, pressing SHIFT should trigger a toast message, just like changing the language does.

My third concern is there are too many functions and too few keys. You have already noticed that. I suppose I can rearrange everything like this:

On hardware keys:
- "✱" (star key).
    - Press to open the Command Palette (no change).
    - Hold to change the text case before or after typing a word (SHIFT key)
- "#"  (pound key)
    - Press to select 123 -> abc -> predictive. (difference 1: there is no separate ABC capitals mode; difference 2: pressing while typing a word leaves the word as-is and switches to the next mode)
    - Hold to change the language (no change)
    
These are the defaults, of course. You will still be able to reassign all functions to all keys from the Settings, like before.
    
On a touchscreen:
- The left F4 key (globe key):
    - Press to select 123 -> abc -> predictive (1. there is no separate ABC capitals mode; 2. changing the mode leaves the current word as-is)
    - Hold to change the language (instead of press to change the language)
    - New icon(s) or labels to make it clear what it does (I hate icons)
- The left F3 key (keyboard key)
    - Press to change the text case before or after typing a word (it becomes a pure SHIFT key and no longer changes the input mode before typing a word)
    - Hold or swipe to select a different keyboard
    - I hate icons

It is the best I can think of. I am not sure if rearranging the functions makes good sense, especially in the case of button phones. I would like to hear some more opinions or at least get a couple of thumbs up before proceding with the changes.

**Comment by maverick74** [comment]
Ok.... about this... (i have not yet re-read your post with the complete attention it deserves - sorry! i've read it but i'll have to do it again with more time)

first a small disclaimer: 
1 - I'll use touchpal as an example because it worked nice in this! it's not that i intend to transform tt9 into touchpal - not even close - It's just trying to use what i think may be a good idea.
2 - What's good for me may not be good for everyone. In fact you may not even agree with it or it may not even be possible to do. **No hard feelings from me if it's rejected**
3 - It's just an idea (and not even a "well thought about" idea, as i did it in a rush...). Maybe it leads to other even better ideas from you... So please, again, don't shoot me ahahahah

here's the "thing":

![idea](https://github.com/user-attachments/assets/1b1bd892-4ef4-42fb-aca9-effd49861597)

**Comment by sspanak** [comment]
Well, sure, do re-read my comment. Meanwhile, I would like to remind that we have to lay out the functions on this keyboard first:

![hardware keypad](https://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Telephone-keypad2.svg/220px-Telephone-keypad2.svg.png)

... and then think about the TT9's virtual keyboard.

Besides, I really don't want to make significant changes or introduce new functions anymore. Please, don't make me do that. It is complicated enough.

**Comment by sspanak** [comment]
But I do believe there is room for improvement. Over time, I have received other reports that changing the modes and the text case is a bit confusing. Heck, sometimes, I confuse myself with my own logic, especially when typing special characters.

Only splitting the current Typing Mode key into Input Mode and Shift is not such a big deal. It will actually reduce the complexity of presenting "abc" and "ABC" as two separate modes, when they are not. It is worth giving a try. I will experiment when preparing v39.0 and may release it if works out well.

**Comment by maverick74** [comment]
In the hardware keyboard... can the d-pad ok/enter be used for any long press/hold function?

Or do we really have to stick to just that 9-keys keyboard?

**Comment by sspanak** [comment]
It can, but it is a bad idea in general, because many apps rely on the "press" and "hold" events to perform specific actions. OK or (ENTER on some devices) is not safe for customizing.

Also, due to other technical reasons, I will not move or customize the on-screen Settings  key.

**Comment by maverick74** [comment]
> Also, due to other technical reasons, I will not move or customize the on-screen Settings key.

I already discarded that idea and was actually thinking - for myself - about "shift" key...

anyway, in the end, the question was more out of curiosity! I didn't intended to even suggest any other changes since you made it clear not to be open to such radical changes (which I really understand!)

**Comment by maverick74** [comment]
Ok, I'm going to suggest another idea (I'm just trying to help! If it doesn't make sense I'll shut up and you don't even need to reply. No hard felling's!)

You have removed the tab key! (I don't know the reason but) why not use that for "shift" and keep the "add word" as a "hold-key" option, as it was?

No change in keyboard layout or anything like that! Just using shift function instead of tab...
(you could still also use the globe key to access numpad, which I believe makes sense...)

**Comment by sspanak** [comment]
Here is [a new version](https://github.com/sspanak/tt9/releases/download/v1.0-inital/tt9-v38.24.apk) with a separate SHIFT key. I needed a couple of days to readjust the muscle memory, but I believe it is much better now. I should much more clear what each key does now.

The language/mode key has two hidden functions. You can swipe vertically to show the list of all installed keyboards; and you can swipe horizontally to quick-switch to the last used keyboard.

Nothing is documented yet but I'll try to describe everything clearly in the manual for the final release.

Also, have in mind this version contains some of the new features and bugfixes for v39.0. There are now dramatic changes, besides the new, so it shouldn't be a big deal for you. But it is nice to know, I guess.

**Comment by maverick74** [comment]
Just installed!!!

I like it!!! 😀

but... how do I switch between English and Portuguese?

**Comment by sspanak** [comment]
> (it's worth noting that to change between languages you have to hold the language/mode key!)

Correct. If a key has a "hold" function, it is usually displayed on top. As I said, I will document this before officially publishing v39.0.

**Comment by sspanak** [comment]
> On CAT S22 there's a speakerphone button that acts like a tab in most places
Can this shift be assigned to it?

Maybe. Go to Settings -> Keypad -> Hotkeys, then click the SHIFT key dropdown. You should see Volume Up/Down or Mute options. Try if any of them works. If not, the key probably has a non-standard code > 255, or Android does not let the keyboards "see" it. There is a similar key on Sonim XP3 that I have tried to use but the key presses never reached my code.

You can also try if [this app](https://play.google.com/store/apps/details?id=aws.apps.keyeventdisplay&hl=en_US) detects the speakerphone key presses. If it does, please send me the logs and I will add support for the key.

**Comment by sspanak** [comment]
Yes, because it hasn't been updated in a while. Try downloading it from [APKPure](https://apkpure.com/keyevent-display/aws.apps.keyeventdisplay).
