### ISSUE TITLE
Touch screen

### ISSUE THREAD

**Issue by AirConditionunit** [sspanak/tt9#624]
I know it says it needs a touch screen but is there a setting that doesn't require touch screen at all? Also does it come with Emojis?

**Comment by sspanak** [comment]
> I know it says it needs a touch screen but is there a setting that doesn't require touch screen at all

Traditional T9 is meant to work on devices with a hardware keys. It can be a dumbphone, it can be a smartphone with a computer keyboard connected to it, or it can even be a TV (you can type with the remote control). It has great support for many devices. All functions are not only accessible using the hardware keys, but you can also assign or disable some of them to your liking.

> does it come with Emojis?

It has some basic emojis and you can add your own if you need to.

All in all, just install and try it out. You've got nothing to lose. Or check [the screenshots](https://github.com/sspanak/tt9?tab=readme-ov-file#-screenshots) on the home page
