### ISSUE TITLE
Switching between input modes in touchscreen-only keyboard?

### ISSUE THREAD

**Issue by bennypr0fane** [sspanak/tt9#635]
When using the hardware keypad, the **#** key is used for cycling through input modes (predictive, Abc, 123...). However, the touchscreen-only keyboard on my Nokia 7.2 (Android 11) shows a **!** and **?** instead of * and **#** respectively, meaning there is no # key. How can I switch between input modes, and make capital letters on the touchscreen-only keyboard?

**Comment by sspanak** [comment]
Use the "keyboard" key for that. When you are typing a work it acts like SHIFT, and when you are not typing, it changes the input mode.

However, I am going to change this in v39.0. There will be a separate SHIFT key and a separate key for changing the modes. I have received several reports that the current logic is confusing, so I've decided to find a way of improving it. I will also document all this in the manual. See [this discussion](https://github.com/sspanak/tt9/issues/622) for more info.
