### ISSUE TITLE
 when you go to the other suggestions in the dictionary using the navigation keys, it does not display them fully

### ISSUE THREAD

**Issue by aAVI904** [sspanak/tt9#648]
Thank you very much for the keyboard!

https://github.com/user-attachments/assets/74b9cca2-ff13-46be-901d-e4f4c5c9f9cd

There is a problem that when you go to the other suggestions in the dictionary using the navigation keys, it does not display them fully, but it remains on the side and you do not see that it is highlighted
Video attached

https://github.com/user-attachments/assets/9c20f8cd-e8bf-481a-807d-461af7392477

**Comment by sspanak** [comment]
Could you please try enabling the "alternative suggestion scrolling" method and see if it fixes the problem? You can find it in Settings -> Appearance, under the Compatibility section.

**Comment by chaimsha** [comment]
thanks
It does help!
But then we will have another problem, the whole row becomes blue and you can't see where you stand
can you check it
Thank you very much
very appreciative

**Comment by sspanak** [comment]
There is a separate bug for this, #640. Please, check it out. If you have any extra information to share, such as the exact steps to reproduce it, or simply your phone make and model, you are welcome to do it in #640.
