### ISSUE TITLE
Is there an easy way to enter contractions, like I'll, don't, etc?

### ISSUE THREAD

**Issue by miki151** [sspanak/tt9#652]
I love the keyboard, but I find that typing in "I'll", for example, takes a lot of keypresses, because you need to enter the apostrophe manually, then switch to abc mode, and enter the two 'l'-s. Am I missing an easier way of entering these?

**Comment by sspanak** [comment]
Of course. Just stay in Predictive mode and type `4166` for `I'll` or `36618` for `don't`. In other words, use the standard Nokia 3310 way of typing.

You can also easily type things like `check-in` = `24325` `146`, and `google.com` = `466453` `1266`, without needing to stop and manually select apostrophes dashes and whatnot. Just press the correct key combination and TT9 will figure it out.

For more complicated cases, you can still stay in Predictive mode and press "0" or "1", then select the correct special character, then continue typing words. You shouldn't need to switch to ABC mode most of the time. It is mostly useful when typing passwords or completely new words missing from the dictionary.

**Comment by miki151** [comment]
This totally changes things, thanks!
