### ISSUE TITLE
Voice input via Voice Access (by Google) 

### ISSUE THREAD

**Issue by TheProgrammer26** [sspanak/tt9#656]
I have Voice Access set up on my phone; however, TT9 doesn't seem to recognize it. Is there a way to fix this issue?

**Comment by sspanak** [comment]
I don't think so. Voice Access is intended for human-to-app interaction, while TT9 is based on the SpeechRecognizer API, which is intended for app-to-app interaction. This means there must be some global app or service that passes the voice input to other apps, like TT9.

I have not used Voice Access, but from what I understand, it is intended to work standalone and not pass-through the recorded words to any other app. Correct me, if I am wrong.

**Comment by TheProgrammer26** [comment]
Correct, however, Voice Access also has a feature "Speach to Text." Whenever there is a text field, I can start speaking and it will input it into words.
