### ISSUE TITLE
Request for help. would it be possible to please add the option for contacts to default to normal text and not prediction

### ISSUE THREAD

**Issue by yh26vh26** [sspanak/tt9#661]
would it be possible to please add the option for contacts to default to normal text and not prediction 
also with the default usually set to prediction but that it will automatically catch when entering contacts 
and also when adding a new contact to send a text message in sms messages 
usually people want it to be text normal and not predictive like there is in Nokia even if it is predictive but in contacts it is not predictive only if you want you can change it by the star.
thank you very much

**Comment by sspanak** [comment]
I'll assume by "normal" mode you mean "ABC" mode.

There are many different contacts and SMS apps. It is not possible to detect them all and guarantee TT9 will start up in ABC mode in each one of them. Sorry, I can't do it.

Anyway, you can change the input mode to ABC or even 123 in any app, including your Contacts and SMS apps. It is just not the star key, but the pound (#) key. See [the manual](https://github.com/sspanak/tt9/blob/master/docs/help/help.en.md#function-keys) for more info about the function keys. And if you want, you can reconfigure all functions from Settings -> Keypad -> Hotkeys.

Having said the above, I don't think it is worth the effort working on this.
