### ISSUE TITLE
add in "Select Shortcut Keys"

### ISSUE THREAD

**Issue by chaimsha** [sspanak/tt9#663]
Is there a possibility to please add in "Select Shortcut Keys" also a long press on the confirmation key [- middle].

**Comment by sspanak** [comment]
If you are talking about the OK or ENTER key, I have deliberately omitted it from the key list for security reasons. Just like the "Hang Up" key, it is very important for all apps and Android itself. I don't want to risk with things like bricked phones, not being able to select things, or press buttons, or switch between apps.

On the other hand, if I am hoping to find free time to allow using (almost) any key, like in games, where you can just press some key to save it as a hotkey, as opposed to selecting from a list. This will enable all special keys on all devices.
