### ISSUE TITLE
Keyboard switches to `English` capitalised mode when removing a word

### ISSUE THREAD

**Issue by tandy-1000** [sspanak/tt9#664]
I have run in to this issue since upgrading to v38 / v39 I think?

When using `english` mode, if you enter a word, then clear it, the keyboard switches to `English` mode.

This has made the keyboard very difficult to use for me because I have to switch back to `english` mode.
I personally never use capitalisation, so it would be nice to configure this.

Predictive settings are:
auto space - on
auto cap - off
learn word pairs - on
word recomp - on

**Comment by sspanak** [comment]
Yes, this comes with word recomposing. When you start erasing a word, TT9 will automatically switch to its text case, to preserve the way it looks. And after you erase it completely, it switches to capitalized mode. 

I am not sure if there is an easy way to fix this, but I'll see what I can do. Meanwhile, if recomposing is not super important to you, disable it to avoid unexpected text case switching.

**Comment by tandy-1000** [comment]
recomposing is a helpful feature, maybe the best thing would just be an option to enable or disable certain modes? Like realisatically, I'd just enable `english`, `abc`, `123` which would simplify things further for me

**Comment by sspanak** [comment]
There are no separate lowercase and uppercase modes. It is not that easy, unfortunately.
