### ISSUE TITLE
T9 Mode automatically capatalized / no lower case option for abc

### ISSUE THREAD

**Issue by kosherboynewb** [sspanak/tt9#666]
I used to use an old version which I downloaded the apk from guthub. Recently i got the latest version from playstore (then it was holding by v. 39). I bumped into 2 issues.
1) On my old version there was 2 ABC options one was capital letters and one was lower case. On the new one it dissapeared.
2) When using the T9 option it by default is on capital letters and the only way to get it to lower case is by backspacing a word and then it switches to lower case.
I am using a rooted TCL Flip 2 flip phone which I installed Gapps with a magisk module.
Thanks so much.
PS Are you bringing back the press ok to answer in google chat?

**Comment by sspanak** [comment]
It's because there is a separate Shift key now. The Input Mode key formerly performed two functions, from v40.0 on, it actually only changes the mode.

See the [v40.0 manual](https://github.com/sspanak/tt9/blob/v40.0/docs/help/help.en.md#shift-key-default-press-) for more info.

**Comment by kosherboynewb** [comment]
What is the easiet way for me to have the first letter capitalized when I am typing on abc mode?
