### ISSUE TITLE
Recomposing / re-editing only suggests words starting with the same letters.

### ISSUE THREAD

**Issue by discoball78** [sspanak/tt9#668]
Sspanak, l'm a long time user of Traditional T9 - I'd like to first give you high props for taking up this projecting and doing the work you have done, really very very well done mate. I was so surprised when revisiting T9, as I had used it while it was still 'dead' and not maintained anymore. After coming back to a new phone this year and suddenly saw that you had taken on the project on a given it life again!

The last update I took was the first release that included recomposing (2 updates ago). I just updated to the latest version and noticed this behavior still present, so figured I'd report this in.

When typing in a hurry and moving on to the next word, realizing that the default word was not the desired word, backspacing to it does not present the normal 'popular' suggestion list anymore, only words starting with the same letters from that incorrectly accepted word. User must then delete sometimes almost the whole word in order to see the normal suggestion list again. I've added two screenshots of both the default list Vs the recompose list.

The demonstrated scenario is a simple one where I accepted the word 'no' when what I really wanted was 'on'. When backspacing back to the word, I only get options for words starting with 'no'. From my personal use, this renders the recompose function redundant for almost any error I make, as the majority of my mistakes stem from accepting the wrong suggested word.

Another example for a larger word: Want to type 'Subnet', accidentally press space to accept the first suggestion of 'Stand'. Backspace back to the word and are only presented with words starting with Stand, Stan, Sta, St as the user progressively backspaces toward the start of the word. Have to backspace all the way back to 'S' to be able to find 'subnet'.

From a user perspective, was hoping to see the default set of words offered again (for that key combination), when backspacing back to it. This way the user can select the word they intended in the first place.

Screenshots to follow, thanks again for your work. Joe.

![Expected Suggestion List](https://github.com/user-attachments/assets/a9bd90e0-0572-4cdc-b21b-e925f7452da6)
![Recompose List](https://github.com/user-attachments/assets/373c3923-149d-41e5-8add-ccc2cd6e072e)

**Comment by sspanak** [comment]
It's because I wasn't sure how to do it. My old Nokia phones don't have this feature and I didn't have a reference, so I just assumed preserving the last word would make more sense. But it is bugging me too and I'll fix it in the next release. 

For the time being, after pressing Backspace, also hit "Clear Filter" (default: DPAD Down) and you will see the "normal" word list.

> l'm a long time user of Traditional T9 - I'd like to first give you high props for taking up this projecting and doing the work you have done, really very very well done mate. I was so surprised when revisiting T9, as I had used it while it was still 'dead' and not maintained anymore. After coming back to a new phone this year and suddenly saw that you had taken on the project on a given it life again!

Thanks! Indeed, it has come a long way, you could say it is a completely different keyboard today. It is because I am doing a lot of hard work, but also thanks to the people who have helped with ideas, bug fixing, testing on their devices, and guiding me how to add new languages that I don't speak. It is truly a community-made product.

**Comment by discoball78** [comment]
What is your weapon of choice at the moment? I'd be happy to compare 
notes with you, but I also don't want to mess this Github thread up with 
off-topic chat. PM?


------ Original Message ------
From "Dimo Karaivanov" ***@***.***>
To "sspanak/tt9" ***@***.***>
Cc "discoball78" ***@***.***>; "Author" 
***@***.***>
Date 16/11/2024 6:55:19 AM
Subject Re: [sspanak/tt9] Recomposing / re-editing only suggests words 
starting with the same letters. (Issue #668)

**Comment by sspanak** [comment]
> What is your weapon of choice at the moment? I'd be happy to compare notes with you

A touchscreen, unfortunately. I can't a solid working equivalent at a reasonable price.

> don't want to mess this Github thread up with off-topic chat. PM?

We've cleared out the main problem in the first two comments. I approve the off topic below.

**Comment by discoball78** [comment]
In terms of the Qin phones, I amended a typo that I made in my post earlier. I now have the **F22 Pro**. I've been using it since I received it in late July (so approximately four months), the keypad was better, but I have noticed only just this week the very occasional missed keystroke for the center (d-pad) button and the number 8 key, we'll see how things go. When I was using the F21, like yourself - yes the keypad started failing fairly early on, and it got pretty bad. The phone was just so cute that I honestly couldn't let it go, so I just put up with the condition, for a long time!

I documented my experiences with the F21 in this thread, and it does echo your experiences: 
[Qin F21 Pro – Daily Driver diary thread “Almost great” but….](https://xdaforums.com/t/qin-f21-pro-daily-driver-diary-thread-almost-great-but.4508937/)

Funny part is you'll see me talking about the T9 app, before you reactivated the project.

The firmware in my F22 seems to be the same as the F21, as I had basically exactly the same issues. Which was handy as I guess it helped to resolve/work around them faster when I got the F22.

Resource threads that helped me greatly while breaking in the F22:

[Review after 1 Month of use: Duoqin F22 Pro
](https://www.reddit.com/r/dumbphones/comments/1cxof5m/review_after_1_month_of_use_duoqin_f22_pro/
)[Made a guide for rooting/microg the Qin F22 Pro
](https://www.reddit.com/r/dumbphones/comments/15yb2yx/made_a_guide_for_rootingmicrog_the_qin_f22_pro/
)[Taking Control of the Xiaomi Qin F22 Pro](https://binboupan.github.io/2023/08/qin-f22-pro/)](https://binboupan.github.io/2023/08/qin-f22-pro/
(and of course your T9 app!)

With the F22 I struggled to get Whatsapp to stay alive, but the above thread explained 'systemizing' apps, which resolved that for me. The power management seemed to work out OK for other apps I use, after messing around with battery optimization settings for them.

The assisted dialing issue was worked around as per my F21 thread notes.

I found that the missed call/message problem started happening when I installed my own selected apps (on the F21), moving back to the original system apps (even though they are very featureless) resolved that. I stuck with this approach on the F22. I was willing to make a number of tradeoffs and give up some luxuries in order to use these cute phones :)

I was curious as looking through the issues list, I see some phones that I was not aware of existing, sometimes no matter how much you search you can't find everything. Do you have a list somewhere of all the 'known' T9 keypad phones that are currently available? I'd love to see what else is out there. I honestly find these Qin phones so cute, so I hope to use this for a while to come....

Being a father/raising a family leaves me no time these days to be messing around with firmwares and hacks etc etc like my younger days. So I just stuck with the most straightforward ways of getting the phone over the line, and fit for day to day service.

**Comment by discoball78** [comment]
In summary though, when all is said and done, I have this F22 Pro running exactly how I want it, and if the keypad stays good, this phone is like a a dream come true for me, I'm so happy with it :) It's not as small/cute as the F21, but the keypad was just so horrible that unfortunately I had to eventually move on.

**Comment by sspanak** [comment]
I follow [Jose Briones](https://www.dumbphones.org/). He lives in the USA, so most of the phones he reviews are for the North America region. Even if you are not going to buy any of them, it may be a good source of education.

As for the Qin F22 Pro, I would have probably tried it, but I don't like flat keypads with no space between the keys. I make too many mistakes when I type. So, for me, the search continues...

**Comment by stianhoiland** [comment]
Just wanted to chime in on this issue and say that I experience the reverse, i.e. that I want the recomposing to preserve the original/stem word and that it is very confusing when recomposition activates and changes the word to something potentially completely different. Not sure what the solution is.

**Comment by sspanak** [comment]
The last word you typed is usually the first. There are small exceptions, but it is what it is. I do not plan to change the way it works.
