### ISSUE TITLE
Option to switch microphone with clipboard

### ISSUE THREAD

**Issue by maverick74** [sspanak/tt9#672]
I never use the "microphone" function but I constantly use the clipboard!

Would it be easy to add an option to switch the two functions (puting the clipboard as the major button function accessible with a normal press and the "microphone" accessible with a long press) and would you agree with the idea?

If not, you can close this 🙂

thank you

**Comment by sspanak** [comment]
This has been bugging me since I added that combined key. I also think the keyboard should be more focused on typing, so I will reverse the functions. However, I do not plan any customizations. I don't have that much free time.

**Comment by maverick74** [comment]
> I also think the keyboard should be more focused on typing, so I will reverse the functions.

**That will work fine for me :)**. 
I keep hitting the mic button over and over (and over)... I avoided creating this bug for a while, as i don't want to abuse... but yesterday was "the water drop"

> I don't have that much free time.

yeah... i know how that feels :(
_it's always important to remember to save some time for yourself_
