### ISSUE TITLE
Feature Request: Keys to right side for easier typing (1,4,7! are too far to reach easily)

### ISSUE THREAD

**Issue by luthis1124** [sspanak/tt9#680]
Should be really simple to implement, have an option to change the order of the columns. Put the typing keys on the right, and the backspace column on the left side. 

It's too far on larger screens to use one-handed, see the layout by https://github.com/dessalines/thumb-key

Much better, it's all in easy reach. Something like this:

![image](https://github.com/user-attachments/assets/43af0ff3-c031-4806-9aa6-3dc805f49864)

**Comment by sspanak** [comment]
Reordering the columns is not simple to implement at all. I am not sure what makes you think that.

To solve the problem, I can add a maximum width setting. TT9 already supports dragging to the left/right, so when you make it narrower than the screen, you would be able to pull it to the right.

Looking from another perspective, maybe the device is too big for your hands? How do you use all other apps, if you can't reach the far side of the screen?
