### ISSUE TITLE
No software SEND function - possible via hardware keys?

### ISSUE THREAD

**Issue by r0usch** [sspanak/tt9#77]
Hi, love the keyboard so far and want to start by saying that I am not an experienced Android dev.

I'm using the Xiaomi Qin F21 Pro and am using a few apps without a send button next to the text input. Using the enter key (when remapped) also does nothing. I'm guessing this is because the SEND function is a softkey function and can't be remapped to a hardware based key, as evidenced by people trying (and failing) to do so with Bluetooth keyboards on Android. Would it be possible to, near to or next to the predictive text at the bottom of the screen, add a software-based SEND function to work-around this issue? It's making certain text fields incredibly difficult to fill out - I type what I want in T9 then have to switch to the AOSP keyboard just to press send. 

Thanks.

**Comment by sspanak** [comment]
Yes, I've noticed the same and I've taken care of it in #51. Currently, it is in `old-skool-experience` branch. I am going to test a bit and merge it in a couple of days.

Some background info about the problem: 
1. It doesn't matter if it is a hardware or a software key. All commands go through a so called "input connection" and it is possible to interact with it anywhere in the code.
2. The Center/OK key is not the same as the Enter key on a full-sized keyboard. As a matter of fact, it is theoretcially possible to build a keyboard that has both. And it is up to the application to decide what to do when each of them are pressed.
