### ISSUE TITLE
Non-floating CandidateView layout

### ISSUE THREAD

**Issue by TomJansen** [sspanak/tt9#90]
The Candidate screen is floating, and thus often times blocks/obstructs the input field. This happens often in for example WhatsApp, or other apps where the input field is at the bottom of the screen. It would be nice if the CandidateView was part of the SoftKey UI.

However, when the vertical option (#28) is implemented, a floating view would be desireable. Nokia's have a vertical candidate view directly under the word, but I am not sure if this is even possible in Android

**Comment by sspanak** [comment]
Agreed, this is extremely annoying. Unfortunately, I don't have a solution at the moment.

I have found it is possible to make it "push" the application up, but this causes constant re-drawing and re-intialization, which is not desirable. I have also tried to make it stay permanenly on, even if empty, but this causes other visual issues.

If you have any ideas, please, be my guest.

As for #28. I cannot picture the entire thing yet, but I think I have an idea. From what I know, it is not possible to attach the suggestions to the input field, but they can surely fit in the place of the OK button. This is probably the way, but I need to research a bit more.

**Comment by TomJansen** [comment]
I am not sure, but maybe this bug be fixed by rewriting the CandidateView java code into a View inside the mainview.xml? like this?
`<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
	android:layout_width="match_parent"
	android:layout_height="76dp"
	android:orientation="vertical">

	<View
		android:id="@+id/candidate_bar"
		android:layout_width="match_parent"
		android:layout_height="0dp"
		android:layout_weight="1"
		android:background="@color/candidate_background"
		android:orientation="horizontal"
		android:scrollbars="none"

		android:fadingEdge="horizontal"
		android:scrollbarAlwaysDrawHorizontalTrack="false"
		android:scrollbarAlwaysDrawVerticalTrack="false">
	</View>

	<LinearLayout
		android:id="@+id/softkey_view"
		android:layout_width="match_parent"
		android:layout_height="48dp"
		android:background="@drawable/bggradient"
		android:baselineAligned="true"
		android:orientation="horizontal">
		<Button />
		<Button/>
		<Button />
	</LinearLayout>
</LinearLayout>
`
And then adding a <TextView> for each word programatically in the java file as childeren to `candidate_bar`

**Comment by TomJansen** [comment]
I almost have something working with recyclerview.
