### ISSUE TITLE
Russian dictionary

### ISSUE THREAD

**Issue by postpersonality** [sspanak/tt9#94]
Please consider using cyrillic-only dictionary 
https://github.com/hingston/russian/blob/master/10000-russian-words-cyrillic-only.txt

I doubt it even possible to enter something like [quot](https://github.com/hingston/russian/blob/master/10000-russian-words.txt#L8)  while being on Russian layout.

Thanks for the wonderful continuation/rework of the app!

**Comment by sspanak** [comment]
I have indeed used a word list from that repo, but it is the 100000 word list, not the 10000 list. 10000 words are really very few for such a dictionary.

Either way, I did make an effort to clean up the file from nonsense words. I even double checked it a moment ago and I don't see any Latin characters there. Have you actually noticed anything wrong? If yes, could you point me to the specific line in the `ru-utf8.txt` file?

**Comment by postpersonality** [comment]
Oh, I see where I was wrong. I've looked into [the original file](https://github.com/hingston/russian/blob/master/100000-russian-words.txt) you link [in the docs](https://github.com/sspanak/tt9/blob/master/docs/ruWordlistReadme.txt). And it contains useless words like "^" or "quotes". 
Now I see you use dictionaries from assets folder, and they are filtered from the garbage. Thank you! Sorry for taking your time.
